/** Audit trail used for admin notifications and force-sale reporting in every mode. */
import { isClientMode } from "./install";
import { serverLogAudit, serverGetAuditLog, serverGetRecentEvents } from "./server-api";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
export interface AuditEntry { id: string; entityType: "medicine" | "sale" | "customer" | "purchase" | "supplier" | "category"; entityId: string; action: "add" | "edit" | "delete" | "force-sale"; username?: string; userId?: string; medicineName?: string; quantity?: number; price?: number; timestamp: string; }
interface ElectronAuditAPI { add: (entry: AuditEntry) => Promise<boolean>; forEntity: (entityType: string, entityId: string) => Promise<AuditEntry[]>; since: (isoTimestamp: string) => Promise<AuditEntry[]>; }
function api(): ElectronAuditAPI | null { if (typeof window === "undefined") return null; return (window as unknown as { electronAPI?: { auditLog?: ElectronAuditAPI } }).electronAPI?.auditLog ?? null; }
function actor(username?: string, userId?: string) { const u = useSession.getState().user; return { username: username ?? u?.username, userId: userId ?? u?.id }; }
async function write(entry: AuditEntry) { try { if (isClientMode()) await serverLogAudit(entry); else await api()?.add(entry); } catch (e) { console.error("[audit] failed", e); } }
export async function logMedicineAudit(entry: Omit<AuditEntry, "id" | "timestamp" | "entityType">) { const a=actor(entry.username,entry.userId); await write({ ...entry, ...a, entityType: "medicine", id: crypto.randomUUID(), timestamp: new Date().toISOString() }); }
export async function logSaleEvent(saleId: string, amount: number, username?: string, userId?: string) { const a=actor(username,userId); await write({ id: crypto.randomUUID(), entityType: "sale", entityId: saleId, action: "add", ...a, price: amount, timestamp: new Date().toISOString() }); try { const sale=useProjectStore.getState().data?.sales.find(s=>s.id===saleId); if(!sale)return; for(const item of sale.items){if(!item.forcedSale)continue;const medicine=useProjectStore.getState().data?.medicines.find(m=>m.id===item.medicineId);await logForceSaleEvent(saleId,medicine?.name??"item",item.quantity,a.username,a.userId,item.salePrice);}}catch(e){console.error("[audit] force-sale event failed",e);} }
export async function logForceSaleEvent(saleId: string, medicineName: string, quantity: number, username?: string, userId?: string, price?: number) { const a=actor(username,userId); await write({ id: crypto.randomUUID(), entityType: "sale", entityId: saleId, action: "force-sale", medicineName, quantity, ...a, price, timestamp: new Date().toISOString() }); }
export async function logCustomerAddEvent(customerId: string, name: string, username?: string, userId?: string) { const a=actor(username,userId); await write({ id: crypto.randomUUID(), entityType: "customer", entityId: customerId, action: "add", ...a, medicineName: name, timestamp: new Date().toISOString() }); }
export async function getMedicineAuditLog(medicineId: string): Promise<AuditEntry[]> { try { if(isClientMode())return ((await serverGetAuditLog("medicine",medicineId)).entries as AuditEntry[])??[]; return (await api()?.forEntity("medicine",medicineId))??[]; } catch { return []; } }
export async function getRecentEvents(sinceIso: string): Promise<AuditEntry[]> { try { if(isClientMode())return ((await serverGetRecentEvents(sinceIso)).entries as AuditEntry[])??[]; return (await api()?.since(sinceIso))??[]; } catch { return []; } }
