import type { CatalogCommand } from "@/lib/command-catalog";

/** Additional commands kept separate so the main catalog stays maintainable. */
export const EXTRA_COMMAND_CATALOG: CatalogCommand[] = [
  { id:"open-help", label:"Open Help Center", description:"Open pharmacy help and What's New", to:"/app/help", keywords:"help guide documentation whats new" },
  { id:"new-message", label:"New Message", description:"Open the internal pharmacy message composer", to:"/app/messages", permission:"messages", keywords:"message send admin notify" },
  { id:"open-patient-report", label:"Patient History Report", description:"Open patient purchase history inside Reports", to:"/app/reports", permission:"reports", keywords:"patient history purchases customer" },
  { id:"open-staff-report", label:"Staff Performance", description:"Open staff performance reporting", to:"/app/reports", permission:"reports", keywords:"staff employee performance sales" },
  { id:"open-profit-analysis", label:"Profit Analysis", description:"Open profit and margin analysis", to:"/app/reports", permission:"reports", keywords:"profit margin earnings" },
  { id:"open-sales-history", label:"Sales History", description:"Open historical sales reporting", to:"/app/reports", permission:"reports", keywords:"sales history transactions" },
  { id:"open-purchase-history", label:"Purchase History", description:"Open historical purchase reporting", to:"/app/reports", permission:"reports", keywords:"purchase history suppliers" },
  { id:"open-expiry-list", label:"Expired Stock List", description:"Review expired medicines and batches", to:"/app/inventory", permission:"inventory", keywords:"expired expiry batch loss" },
  { id:"open-near-expiry", label:"Near Expiry List", description:"Review medicines approaching expiry", to:"/app/inventory", permission:"inventory", keywords:"near expiry soon expire" },
  { id:"open-dead-stock", label:"Dead Stock Review", description:"Review inactive stock tying up capital", to:"/app/inventory", permission:"inventory", keywords:"dead stock slow inactive capital" },
  { id:"open-low-stock", label:"Low Stock List", description:"Open medicines below minimum stock", to:"/app/inventory", permission:"inventory", keywords:"low stock minimum reorder" },
  { id:"open-out-of-stock", label:"Out of Stock List", description:"Open medicines with zero stock", to:"/app/inventory", permission:"inventory", keywords:"out stock zero unavailable" },
  { id:"open-reorder-suggestions", label:"Reorder Suggestions", description:"Open smart reorder recommendations", to:"/app/inventory", permission:"inventory", keywords:"reorder suggestions po buying" },
  { id:"open-stock-reconciliation", label:"Stock Reconciliation", description:"Review stock differences and reconciliation", to:"/app/inventory", permission:"inventory", keywords:"reconciliation variance discrepancy" },
  { id:"open-batch-reconciliation", label:"Batch Reconciliation", description:"Compare batch quantities with medicine stock", to:"/app/operations", permission:"operationsBatches", keywords:"batch reconcile quantity" },
  { id:"open-fefo", label:"FEFO Control", description:"Open first-expiry-first-out controls", to:"/app/operations", permission:"operationsBatches", keywords:"fefo fifo batch expiry" },
  { id:"open-return-to-supplier", label:"Return to Supplier", description:"Open return-to-supplier workflow", to:"/app/operations", permission:"operationsReturns", keywords:"supplier return expired damaged" },
  { id:"open-sales-return", label:"Sales Return", description:"Open sales return controls", to:"/app/operations", permission:"operationsReturns", keywords:"sales return refund" },
  { id:"open-stock-transfer", label:"Stock Transfer", description:"Open stock transfer controls", to:"/app/operations", permission:"operations", keywords:"transfer move stock branch" },
  { id:"open-barcode", label:"Barcode Scanner", description:"Open barcode scanning operations", to:"/app/operations", permission:"operationsBarcode", keywords:"barcode scan scanner" },
  { id:"open-units", label:"Unit Management", description:"Open medicine unit controls", to:"/app/operations", permission:"operations", keywords:"unit pack box tablet bottle" },
  { id:"open-finance", label:"Finance Controls", description:"Open pharmacy finance controls", to:"/app/operations", permission:"operations", keywords:"finance cash expenses" },
  { id:"open-p1", label:"P1 Controls", description:"Open phase 1 pharmacy controls", to:"/app/operations", permission:"operations", keywords:"p1 controls" },
  { id:"open-p2", label:"P2 Operations", description:"Open phase 2 pharmacy operations", to:"/app/operations", permission:"operations", keywords:"p2 operations" },
  { id:"open-rack-access", label:"Rack Access Settings", description:"Manage staff access to pharmacy-defined racks", to:"/app/settings", keywords:"rack access staff permission" },
  { id:"open-user-access", label:"User Access Settings", description:"Manage user permissions", to:"/app/settings", keywords:"users permissions access" },
  { id:"open-shortcut-settings", label:"Shortcut Settings", description:"Configure keyboard shortcuts", to:"/app/settings", keywords:"keyboard shortcut hotkey" },
  { id:"open-notification-settings", label:"Notification Settings", description:"Configure pharmacy notification preferences", to:"/app/settings", keywords:"notification alerts settings" },
  { id:"open-backup", label:"Backup & Data Settings", description:"Manage pharmacy backup and data tools", to:"/app/settings", keywords:"backup restore data" },
  { id:"open-workspace", label:"Workspace Settings", description:"Configure workspace behaviour", to:"/app/settings", keywords:"workspace tabs navigation" },
  { id:"open-keyboard-help", label:"Keyboard Navigation Help", description:"Review mouse-free navigation controls", to:"/app/settings", keywords:"keyboard mouse free alt keytips" },
  { id:"start-opening", label:"Start Morning Opening", description:"Run the pharmacy opening workflow", to:"/app/workflows", permission:"operations", keywords:"morning opening start day" },
  { id:"start-closing", label:"Start Daily Closing", description:"Run the end-of-day workflow", to:"/app/workflows", permission:"operations", keywords:"daily closing end day" },
  { id:"start-inventory-review", label:"Start Inventory Review", description:"Review low stock, expiry, dead stock and reconciliation", to:"/app/workflows", permission:"inventory", keywords:"inventory review health" },
  { id:"start-finance-review", label:"Start Finance Review", description:"Review cash, payables and profitability", to:"/app/workflows", permission:"operations", keywords:"finance review cash payable profit" },
  { id:"start-manager-review", label:"Start Manager Review", description:"Run a prioritized pharmacy manager review", to:"/app/workflows", permission:"operations", keywords:"manager review daily" },
  { id:"open-workflow-builder", label:"Workflow Builder", description:"Create and customize pharmacy workflows", to:"/app/workflows", keywords:"workflow builder create customize" },
  { id:"open-intent-queue", label:"Intent Queue", description:"Open prioritized work that needs attention", to:"/app/workflows", keywords:"intent queue priority attention" },
  { id:"open-workflow-history", label:"Workflow History", description:"Review completed workflows and audit history", to:"/app/workflows", keywords:"workflow history audit completed" },
  { id:"open-macro-builder", label:"Macro Builder", description:"Create pharmacy-specific keyboard macros", to:"/app/macros", keywords:"macro automation keyboard" },
  { id:"new-macro", label:"New Pharmacy Macro", description:"Create a new custom pharmacy macro", to:"/app/macros", keywords:"new macro shortcut automation" },
  { id:"open-calculator", label:"Open Calculator", description:"Open the pharmacy calculator", to:"/app/calculator", keywords:"calculator math" },
  { id:"open-reports", label:"Open Reports", description:"Open the complete report workspace", to:"/app/reports", permission:"reports", keywords:"reports analytics" },
  { id:"open-patients-report", label:"Open Patients in Reports", description:"Open patient history through the Reports workspace", to:"/app/reports", permission:"reports", keywords:"patients history report" },
  { id:"open-customer-ledger", label:"Customer Ledger", description:"Open customer ledger controls", to:"/app/operations", permission:"operationsCustomerLedger", keywords:"customer ledger credit khata" },
  { id:"open-supplier-ledger", label:"Supplier Ledger", description:"Open supplier payable ledger", to:"/app/operations", permission:"operationsSupplierLedger", keywords:"supplier ledger payable" },
  { id:"open-message-center", label:"Message Center", description:"Open internal pharmacy messages", to:"/app/messages", permission:"messages", keywords:"message notification admin" },
];
