import type { UserPermissions } from "@/lib/users";

export type CatalogCommand = {
  id: string;
  label: string;
  description: string;
  to: string;
  permission?: keyof UserPermissions;
  keywords?: string;
};

/** Curated commands exposed through Ctrl+K. Route commands are filtered by the user's visible navigation. */
export const COMMAND_CATALOG: CatalogCommand[] = [
  { id:"open-dashboard", label:"Open Dashboard", description:"Go to the pharmacy dashboard", to:"/app", keywords:"home overview" },
  { id:"open-sales", label:"Open Sales / POS", description:"Open the point of sale", to:"/app/sales", permission:"sales", keywords:"sale checkout pos" },
  { id:"open-purchases", label:"Open Purchases", description:"Manage purchases and supplier invoices", to:"/app/purchases", permission:"purchases", keywords:"purchase buy invoice supplier" },
  { id:"open-medicines", label:"Open Medicines", description:"Manage the medicine master and stock", to:"/app/medicines", permission:"medicines", keywords:"drug medicine stock" },
  { id:"open-customers", label:"Open Customers", description:"Open customer records and balances", to:"/app/customers", permission:"customers", keywords:"customer patient account" },
  { id:"open-suppliers", label:"Open Suppliers", description:"Open supplier records and balances", to:"/app/suppliers", permission:"suppliers", keywords:"supplier vendor" },
  { id:"open-reports", label:"Open Reports", description:"Open sales, purchase, profit and patient reports", to:"/app/reports", permission:"reports", keywords:"report analytics profit" },
  { id:"open-operations", label:"Open Pharmacy Operations", description:"Open batches, returns, transfers and ledgers", to:"/app/operations", permission:"operations", keywords:"operations batch return transfer" },
  { id:"open-stocktake", label:"Open Stock Take", description:"Count and reconcile physical inventory", to:"/app/stocktake", permission:"stocktake", keywords:"inventory count reconciliation" },
  { id:"open-racks", label:"Open Racks", description:"Manage pharmacy-defined rack locations", to:"/app/racks", permission:"racks", keywords:"rack shelf location" },
  { id:"open-patients", label:"Open Patients", description:"View patient purchase history", to:"/app/patients", permission:"patients", keywords:"patient history" },
  { id:"open-prescriptions", label:"Open Prescriptions", description:"Manage prescriptions and visits", to:"/app/prescriptions", permission:"prescriptions", keywords:"prescription rx doctor" },
  { id:"open-messages", label:"Open Messages", description:"Open private pharmacy messages", to:"/app/messages", permission:"messages", keywords:"message chat admin" },
  { id:"open-notifications", label:"Open Notifications", description:"Review pharmacy notifications", to:"/app/notifications", permission:"notifications", keywords:"alerts notification" },
  { id:"open-bills", label:"Open Bills", description:"Review completed bills and invoices", to:"/app/bills", permission:"bills", keywords:"invoice receipt bill" },
  { id:"open-categories", label:"Open Categories", description:"Manage medicine categories", to:"/app/categories", permission:"categories", keywords:"category" },
  { id:"open-inventory", label:"Open Inventory", description:"Review inventory controls", to:"/app/inventory", permission:"inventory", keywords:"inventory stock" },
  { id:"open-calculator", label:"Open Calculator", description:"Open the pharmacy calculator", to:"/app/calculator", keywords:"calculator math" },
  { id:"open-workflows", label:"Open Workflow Engine", description:"Start, continue or review workflows", to:"/app/workflows", keywords:"workflow process smart" },
  { id:"open-settings", label:"Open Settings", description:"Manage users, permissions and workspace settings", to:"/app/settings", keywords:"settings users permissions" },
  { id:"new-medicine", label:"New Medicine", description:"Create a medicine record", to:"/app/medicines", permission:"medicines", keywords:"add medicine create drug" },
  { id:"new-purchase", label:"New Purchase", description:"Start a supplier purchase", to:"/app/purchases", permission:"purchases", keywords:"add purchase grn receiving" },
  { id:"new-customer", label:"New Customer", description:"Create a customer record", to:"/app/customers", permission:"customers", keywords:"add customer" },
  { id:"new-supplier", label:"New Supplier", description:"Create a supplier record", to:"/app/suppliers", permission:"suppliers", keywords:"add supplier vendor" },
  { id:"new-stocktake", label:"New Stock Take", description:"Start a physical stock count", to:"/app/stocktake", permission:"stocktake", keywords:"count inventory" },
  { id:"new-rack", label:"Add Rack", description:"Create a pharmacy-defined rack", to:"/app/racks", permission:"racksAdd", keywords:"rack shelf add location" },
  { id:"new-category", label:"New Category", description:"Create a medicine category", to:"/app/categories", permission:"categoriesAdd", keywords:"category add" },
  { id:"new-prescription", label:"New Prescription", description:"Create a prescription record", to:"/app/prescriptions", permission:"prescriptionsAdd", keywords:"rx prescription" },
  { id:"start-fast-sale", label:"Start Fast Sale Workflow", description:"Open the guided sales workflow", to:"/app/workflows", permission:"sales", keywords:"workflow sale pos" },
  { id:"start-purchase-workflow", label:"Start Purchase Workflow", description:"Open the guided receiving workflow", to:"/app/workflows", permission:"purchases", keywords:"workflow purchase grn" },
  { id:"start-stocktake-workflow", label:"Start Stock Take Workflow", description:"Open the guided stock take workflow", to:"/app/workflows", permission:"stocktake", keywords:"workflow count" },
  { id:"start-returns-workflow", label:"Start Returns Workflow", description:"Open the guided returns workflow", to:"/app/workflows", permission:"operations", keywords:"workflow return" },
  { id:"start-closing-workflow", label:"Start Daily Closing Workflow", description:"Open the guided daily closing workflow", to:"/app/workflows", permission:"operations", keywords:"workflow close cash" },
  { id:"workflow-history", label:"Review Workflow History", description:"See who completed which workflow and when", to:"/app/workflows", permission:"operations", keywords:"workflow audit history" },
  { id:"workflow-builder", label:"Open Workflow Builder", description:"Customize pharmacy workflows", to:"/app/workflows", permission:"operations", keywords:"workflow builder admin custom" },
  { id:"smart-workflow", label:"Smart Workflow Review", description:"Open the workflow engine and prioritize current work", to:"/app/workflows", permission:"operations", keywords:"smart priority intent queue" },
  { id:"expiry-review", label:"Review Expiry Alerts", description:"Open operations to review expired and soon-expiring stock", to:"/app/operations", permission:"operations", keywords:"expiry expired soon batch" },
  { id:"low-stock-review", label:"Review Low Stock", description:"Open medicines to review medicines at or below minimum stock", to:"/app/medicines", permission:"medicines", keywords:"low stock reorder" },
  { id:"supplier-payables", label:"Review Supplier Payables", description:"Open operations for supplier balances and invoices", to:"/app/operations", permission:"operations", keywords:"payable supplier due invoice" },
  { id:"customer-ledger", label:"Open Customer Ledger", description:"Review customer credit and payments", to:"/app/operations", permission:"operations", keywords:"khata credit ledger" },
  { id:"supplier-ledger", label:"Open Supplier Ledger", description:"Review supplier payable ledger", to:"/app/operations", permission:"operations", keywords:"supplier ledger payable" },
  { id:"batch-control", label:"Open Batch / FEFO Control", description:"Review batch-level stock and FEFO controls", to:"/app/operations", permission:"operationsBatches", keywords:"batch fefo fifo expiry" },
  { id:"returns-control", label:"Open Returns Control", description:"Review sale and purchase returns", to:"/app/operations", permission:"operationsReturns", keywords:"return refund" },
  { id:"stock-transfer", label:"Open Stock Transfers", description:"Move stock between pharmacy locations", to:"/app/operations", permission:"operations", keywords:"transfer stock" },
  { id:"barcode-tools", label:"Open Barcode Tools", description:"Open barcode and scanner operations", to:"/app/operations", permission:"operationsBarcode", keywords:"barcode scan scanner" },
  { id:"sales-report", label:"Sales Report", description:"Open reports for sales analysis", to:"/app/reports", permission:"reports", keywords:"sales report" },
  { id:"purchase-report", label:"Purchase Report", description:"Open reports for purchase analysis", to:"/app/reports", permission:"reports", keywords:"purchase report" },
  { id:"profit-report", label:"Profit Report", description:"Open reports for profit analysis", to:"/app/reports", permission:"reports", keywords:"profit margin report" },
  { id:"patient-report", label:"Patient Report", description:"Open the patient report tab", to:"/app/reports", permission:"reports", keywords:"patient report history" },
  { id:"customer-report", label:"Customer Report", description:"Open customer reporting", to:"/app/reports", permission:"reports", keywords:"customer report" },
  { id:"supplier-report", label:"Supplier Report", description:"Open supplier reporting", to:"/app/reports", permission:"reports", keywords:"supplier report" },
  { id:"inventory-report", label:"Inventory Report", description:"Open inventory reporting", to:"/app/reports", permission:"reports", keywords:"inventory report stock" },
  { id:"expiry-report", label:"Expiry Report", description:"Open expiry reporting", to:"/app/reports", permission:"reports", keywords:"expiry report expired" },
  { id:"message-center", label:"Message Center", description:"Open internal communication", to:"/app/messages", permission:"messages", keywords:"message center" },
  { id:"notification-center", label:"Notification Center", description:"Open all pharmacy alerts", to:"/app/notifications", permission:"notifications", keywords:"notification alert center" },
  { id:"pinned-items", label:"Pinned Items", description:"Open pinned pharmacy panels", to:"/app/notifications", permission:"viewPinPanel", keywords:"pin pinned" },
  { id:"keyboard-shortcuts", label:"Keyboard Shortcuts", description:"Open shortcut settings", to:"/app/settings", keywords:"shortcut hotkey keyboard" },
  { id:"user-access", label:"User Access", description:"Open user permissions settings", to:"/app/settings", keywords:"users access permission" },
  { id:"rack-access", label:"Rack Access", description:"Open rack access settings", to:"/app/settings", keywords:"rack access permission" },
  { id:"notification-settings", label:"Notification Settings", description:"Configure notification preferences", to:"/app/settings", keywords:"notification preferences" },
  { id:"backup-settings", label:"Backup & Data", description:"Open backup and restore settings", to:"/app/settings", keywords:"backup restore data" },
  { id:"workspace-settings", label:"Workspace Settings", description:"Configure workspace behaviour", to:"/app/settings", keywords:"workspace" },
  { id:"daily-review", label:"Daily Pharmacy Review", description:"Open workflows for a prioritized operational review", to:"/app/workflows", keywords:"daily review manager" },
  { id:"morning-opening", label:"Morning Opening", description:"Start the pharmacy opening workflow", to:"/app/workflows", permission:"operations", keywords:"opening morning" },
  { id:"end-of-day", label:"End of Day", description:"Start the daily closing workflow", to:"/app/workflows", permission:"operations", keywords:"closing end day" },
  { id:"inventory-health", label:"Inventory Health Review", description:"Review stock, batches, expiry and reconciliation", to:"/app/workflows", permission:"inventory", keywords:"inventory health" },
  { id:"finance-health", label:"Finance Health Review", description:"Review cash, payables and profit workflows", to:"/app/workflows", permission:"operations", keywords:"finance cash profit" },
  { id:"command-help", label:"Command Bar Help", description:"Search all available Ctrl+K commands", to:"/app/settings", keywords:"help commands ctrl k" },
];
