import type { UserPermissions } from "@/lib/users";

export type CatalogCommand = {
  id: string;
  label: string;
  description: string;
  to: string;
  permission?: keyof UserPermissions;
  keywords?: string;
};

/** Curated commands exposed through Ctrl+K. Route commands are filtered by the user's visible navigation. */
export const COMMAND_CATALOG: CatalogCommand[] = [
  { id:"open-dashboard", label:"Open Dashboard", description:"Go to the pharmacy dashboard", to:"/app", keywords:"home overview" },
  { id:"open-sales", label:"Open Sales / POS", description:"Open the point of sale", to:"/app/sales", permission:"sales", keywords:"sale checkout pos" },
  { id:"open-purchases", label:"Open Purchases", description:"Manage purchases and supplier invoices", to:"/app/purchases", permission:"purchases", keywords:"purchase buy invoice supplier" },
  { id:"open-medicines", label:"Open Medicines", description:"Manage the medicine master and stock", to:"/app/medicines", permission:"medicines", keywords:"drug medicine stock" },
  { id:"open-customers", label:"Open Customers", description:"Open customer records and balances", to:"/app/customers", permission:"customers", keywords:"customer account" },
  { id:"open-suppliers", label:"Open Suppliers", description:"Open supplier records and balances", to:"/app/suppliers", permission:"suppliers", keywords:"supplier vendor" },
  { id:"open-reports", label:"Open Reports", description:"Open sales, purchase, profit and patient reports", to:"/app/reports", permission:"reports", keywords:"report analytics profit patient history" },
  { id:"open-operations", label:"Open Pharmacy Operations", description:"Open batches, returns, transfers and ledgers", to:"/app/operations", permission:"operations", keywords:"operations batch return transfer" },
  { id:"open-stocktake", label:"Open Stock Take", description:"Count and reconcile physical inventory", to:"/app/stocktake", permission:"stocktake", keywords:"inventory count reconciliation" },
  { id:"open-racks", label:"Open Racks", description:"Manage pharmacy-defined rack locations", to:"/app/racks", permission:"racks", keywords:"rack shelf location" },
  { id:"open-prescriptions", label:"Open Prescriptions", description:"Manage prescriptions and visits", to:"/app/prescriptions", permission:"prescriptions", keywords:"prescription rx doctor" },
  { id:"open-messages", label:"Open Messages", description:"Open private pharmacy messages", to:"/app/messages", permission:"messages", keywords:"message chat admin" },
  { id:"open-bills", label:"Open Bills", description:"Review completed bills and invoices", to:"/app/bills", permission:"bills", keywords:"invoice receipt bill" },
  { id:"open-categories", label:"Open Categories", description:"Manage medicine categories", to:"/app/categories", permission:"categories", keywords:"category" },
  { id:"open-inventory", label:"Open Inventory", description:"Review inventory controls", to:"/app/inventory", permission:"inventory", keywords:"inventory stock" },
  { id:"open-calculator", label:"Open Calculator", description:"Open the pharmacy calculator", to:"/app/calculator", keywords:"calculator math" },
  { id:"open-workflows", label:"Open Workflow Engine", description:"Start, continue or review workflows", to:"/app/workflows", keywords:"workflow process smart" },
  { id:"open-settings", label:"Open Settings", description:"Manage users, permissions and workspace settings", to:"/app/settings", keywords:"settings users permissions" },
  { id:"open-shortcuts", label:"Open Shortcuts", description:"Review all keyboard shortcuts", to:"/app/shortcuts", keywords:"shortcut hotkey keyboard" },
  { id:"open-macros", label:"Open Custom Macros", description:"Create pharmacy-specific shortcut routines", to:"/app/macros", keywords:"macro shortcut automation" },
  { id:"new-medicine", label:"New Medicine", description:"Create a medicine record", to:"/app/medicines", permission:"medicines", keywords:"add medicine create drug" },
  { id:"new-purchase", label:"New Purchase", description:"Start a supplier purchase", to:"/app/purchases", permission:"purchases", keywords:"add purchase grn receiving" },
  { id:"new-customer", label:"New Customer", description:"Create a customer record", to:"/app/customers", permission:"customers", keywords:"add customer" },
  { id:"new-supplier", label:"New Supplier", description:"Create a supplier record", to:"/app/suppliers", permission:"suppliers", keywords:"add supplier vendor" },
  { id:"new-stocktake", label:"New Stock Take", description:"Start a physical stock count", to:"/app/stocktake", permission:"stocktake", keywords:"count inventory" },
  { id:"new-rack", label:"Add Rack", description:"Create a pharmacy-defined rack", to:"/app/racks", permission:"racksAdd", keywords:"rack shelf add location" },
  { id:"new-category", label:"New Category", description:"Create a medicine category", to:"/app/categories", permission:"categoriesAdd", keywords:"category add" },
  { id:"new-prescription", label:"New Prescription", description:"Create a prescription record", to:"/app/prescriptions", permission:"prescriptionsAdd", keywords:"rx prescription" },
  { id:"start-fast-sale", label:"Start Fast Sale Workflow", description:"Open the guided sales workflow", to:"/app/workflows", permission:"sales", keywords:"workflow sale pos" },
  { id:"start-purchase-workflow", label:"Start Purchase Workflow", description:"Open the guided receiving workflow", to:"/app/workflows", permission:"purchases", keywords:"workflow purchase grn" },
  { id:"start-stocktake-workflow", label:"Start Stock Take Workflow", description:"Open the guided stock take workflow", to:"/app/workflows", permission:"stocktake", keywords:"workflow count" },
  { id:"start-returns-workflow", label:"Start Returns Workflow", description:"Open the guided returns workflow", to:"/app/workflows", permission:"operations", keywords:"workflow return" },
  { id:"start-closing-workflow", label:"Start Daily Closing Workflow", description:"Open the guided daily closing workflow", to:"/app/workflows", permission:"operations", keywords:"workflow close cash" },
  { id:"workflow-history", label:"Review Workflow History", description:"See who completed which workflow and when", to:"/app/workflows", permission:"operations", keywords:"workflow audit history" },
  { id:"workflow-builder", label:"Open Workflow Builder", description:"Customize pharmacy workflows", to:"/app/workflows", permission:"operations", keywords:"workflow builder admin custom" },
  { id:"smart-workflow", label:"Smart Workflow Review", description:"Open the workflow engine and prioritize current work", to:"/app/workflows", permission:"operations", keywords:"smart priority intent queue" },
  { id:"expiry-review", label:"Review Expiry Alerts", description:"Open operations to review expired and soon-expiring stock", to:"/app/operations", permission:"operations", keywords:"expiry expired soon batch" },
  { id:"low-stock-review", label:"Review Low Stock", description:"Open medicines to review medicines at or below minimum stock", to:"/app/medicines", permission:"medicines", keywords:"low stock reorder" },
  { id:"supplier-payables", label:"Review Supplier Payables", description:"Open operations for supplier balances and invoices", to:"/app/operations", permission:"operations", keywords:"payable supplier due invoice" },
  { id:"customer-ledger", label:"Open Customer Ledger", description:"Review customer credit and payments", to:"/app/operations", permission:"operations", keywords:"khata credit ledger" },
  { id:"supplier-ledger", label:"Open Supplier Ledger", description:"Review supplier payable ledger", to:"/app/operations", permission:"operations", keywords:"supplier ledger payable" },
  { id:"batch-control", label:"Open Batch / FEFO Control", description:"Review batch-level stock and FEFO controls", to:"/app/operations", permission:"operationsBatches", keywords:"batch fefo fifo expiry" },
  { id:"returns-control", label:"Open Returns Control", description:"Review sale and purchase returns", to:"/app/operations", permission:"operationsReturns", keywords:"return refund" },
  { id:"stock-transfer", label:"Open Stock Transfers", description:"Move stock between pharmacy locations", to:"/app/operations", permission:"operations", keywords:"transfer stock" },
  { id:"barcode-tools", label:"Open Barcode Tools", description:"Open barcode and scanner operations", to:"/app/operations", permission:"operationsBarcode", keywords:"barcode scan scanner" },
  { id:"sales-report", label:"Sales Report", description:"Open reports for sales analysis", to:"/app/reports", permission:"reports", keywords:"sales report" },
  { id:"purchase-report", label:"Purchase Report", description:"Open reports for purchase analysis", to:"/app/reports", permission:"reports", keywords:"purchase report" },
  { id:"profit-report", label:"Profit Report", description:"Open reports for profit analysis", to:"/app/reports", permission:"reports", keywords:"profit margin report" },
  { id:"patient-report", label:"Patient Report", description:"Open the patient history report tab", to:"/app/reports", permission:"reports", keywords:"patient report history" },
  { id:"customer-report", label:"Customer Report", description:"Open customer reporting", to:"/app/reports", permission:"reports", keywords:"customer report" },
  { id:"supplier-report", label:"Supplier Report", description:"Open supplier reporting", to:"/app/reports", permission:"reports", keywords:"supplier report" },
  { id:"inventory-report", label:"Inventory Report", description:"Open inventory reporting", to:"/app/reports", permission:"reports", keywords:"inventory report stock" },
  { id:"expiry-report", label:"Expiry Report", description:"Open expiry reporting", to:"/app/reports", permission:"reports", keywords:"expiry report expired" },
  { id:"message-center", label:"Message Center", description:"Open internal communication", to:"/app/messages", permission:"messages", keywords:"message center" },
  { id:"notification-center", label:"Notification Center", description:"Open all pharmacy alerts", to:"/app/notifications", permission:"notifications", keywords:"notification alert center" },
  { id:"pinned-items", label:"Pinned Items", description:"Open pinned pharmacy panels", to:"/app/notifications", permission:"viewPinPanel", keywords:"pin pinned" },
  { id:"keyboard-shortcuts", label:"Keyboard Shortcuts", description:"Open shortcut settings", to:"/app/settings", keywords:"shortcut hotkey keyboard" },
  { id:"user-access", label:"User Access", description:"Open user permissions settings", to:"/app/settings", keywords:"users access permission" },
  { id:"rack-access", label:"Rack Access", description:"Open rack access settings", to:"/app/settings", keywords:"rack access permission" },
  { id:"notification-settings", label:"Notification Settings", description:"Configure notification preferences", to:"/app/settings", keywords:"notification preferences" },
  { id:"backup-settings", label:"Backup & Data", description:"Open backup and restore settings", to:"/app/settings", keywords:"backup restore data" },
  { id:"workspace-settings", label:"Workspace Settings", description:"Configure workspace behaviour", to:"/app/settings", keywords:"workspace" },
  { id:"daily-review", label:"Daily Pharmacy Review", description:"Open workflows for a prioritized operational review", to:"/app/workflows", keywords:"daily review manager" },
  { id:"morning-opening", label:"Morning Opening", description:"Start the pharmacy opening workflow", to:"/app/workflows", permission:"operations", keywords:"opening morning" },
  { id:"end-of-day", label:"End of Day", description:"Start the daily closing workflow", to:"/app/workflows", permission:"operations", keywords:"closing end day" },
  { id:"inventory-health", label:"Inventory Health Review", description:"Review stock, batches, expiry and reconciliation", to:"/app/workflows", permission:"inventory", keywords:"inventory health" },
  { id:"finance-health", label:"Finance Health Review", description:"Review cash, payables and profit workflows", to:"/app/workflows", permission:"operations", keywords:"finance cash profit" },
  { id:"command-help", label:"Command Bar Help", description:"Search all available Ctrl+K commands", to:"/app/settings", keywords:"help commands ctrl k" },
  { id:"simple-purchase", label:"Simple Purchase", description:"Open the quick everyday purchase tab", to:"/app/purchases", permission:"purchases", keywords:"simple purchase quick buy" },
  { id:"purchase-cycle", label:"Purchase Cycle", description:"Open the purchase to GRN to invoice to payable workflow", to:"/app/purchases", permission:"purchases", keywords:"purchase cycle grn invoice payable" },
  { id:"inventory-overview", label:"Inventory Overview", description:"Open the inventory overview tab", to:"/app/inventory", permission:"inventory", keywords:"inventory overview" },
  { id:"inventory-reorder", label:"Smart Reorder", description:"Open smart reorder recommendations", to:"/app/inventory", permission:"inventory", keywords:"reorder purchase order low stock" },
  { id:"inventory-expiry", label:"Expiry & Batches", description:"Open expiry and batch inventory controls", to:"/app/inventory", permission:"inventory", keywords:"expiry batches" },
  { id:"inventory-dead-stock", label:"Dead Stock", description:"Review slow-moving and dead inventory", to:"/app/inventory", permission:"inventory", keywords:"dead stock slow moving" },
  { id:"inventory-reconciliation", label:"Inventory Reconciliation", description:"Compare batch and medicine stock", to:"/app/inventory", permission:"inventory", keywords:"reconcile discrepancy variance" },
  { id:"operations-barcode", label:"Barcode Operations", description:"Open barcode operations", to:"/app/operations", permission:"operationsBarcode", keywords:"scan barcode" },
  { id:"operations-batches", label:"Batch Controls", description:"Open batch and FEFO controls", to:"/app/operations", permission:"operationsBatches", keywords:"batch fefo" },
  { id:"operations-returns", label:"Returns", description:"Open return controls", to:"/app/operations", permission:"operationsReturns", keywords:"returns refund" },
  { id:"operations-customer-ledger", label:"Customer Ledger", description:"Open customer ledger controls", to:"/app/operations", permission:"operationsLedger", keywords:"customer ledger khata" },
  { id:"operations-supplier-ledger", label:"Supplier Ledger", description:"Open supplier ledger controls", to:"/app/operations", permission:"operationsLedger", keywords:"supplier ledger payable" },
  { id:"operations-units", label:"Units", description:"Open medicine unit management", to:"/app/operations", permission:"operationsUnits", keywords:"units pack box tablet" },
  { id:"operations-finance", label:"Finance", description:"Open finance controls", to:"/app/operations", permission:"operationsFinance", keywords:"finance cash expense" },
  { id:"operations-p1", label:"P1 Controls", description:"Open phase 1 operational controls", to:"/app/operations", permission:"operations", keywords:"p1 controls" },
  { id:"operations-p2", label:"P2 Operations", description:"Open phase 2 operational controls", to:"/app/operations", permission:"operations", keywords:"p2 operations" },
  { id:"rack-management", label:"Rack Management", description:"Open rack creation and management", to:"/app/racks", permission:"racks", keywords:"rack location shelf" },
  { id:"prescription-list", label:"Prescription List", description:"Review existing prescriptions", to:"/app/prescriptions", permission:"prescriptions", keywords:"prescriptions list" },
  { id:"patient-history-report", label:"Patient Purchase History", description:"Open patient history inside Reports", to:"/app/reports", permission:"reports", keywords:"patient history purchase history" },
  { id:"staff-performance-report", label:"Staff Performance Report", description:"Review staff sales and performance", to:"/app/reports", permission:"reports", keywords:"staff performance employee" },
  { id:"reports-explorer", label:"Report Explorer", description:"Explore all available report views", to:"/app/reports", permission:"reports", keywords:"report explorer analytics" },
  { id:"macro-builder", label:"Macro Builder", description:"Create a custom pharmacy macro", to:"/app/macros", keywords:"macro builder automation" },
  { id:"workflow-suggestions", label:"Workflow Suggestions", description:"See the engine's recommended next actions", to:"/app/workflows", keywords:"workflow suggestions smart next" },
  { id:"intent-queue", label:"Intent Queue", description:"Open prioritized work that needs attention", to:"/app/workflows", keywords:"intent queue priority" },
  { id:"workflow-audit", label:"Workflow Audit", description:"Review completed workflow history", to:"/app/workflows", keywords:"workflow audit history" },
  { id:"new-workflow", label:"New Workflow", description:"Create a pharmacy-specific workflow", to:"/app/workflows", keywords:"workflow create builder" },
  { id:"new-macro", label:"New Custom Macro", description:"Create a new pharmacy macro", to:"/app/macros", keywords:"macro create shortcut" },
  { id:"review-messages", label:"Review Unread Messages", description:"Open messages that still need attention", to:"/app/messages", permission:"messages", keywords:"unread message" },
  { id:"review-notifications", label:"Review Alerts", description:"Open pharmacy notifications and warnings", to:"/app/notifications", permission:"notifications", keywords:"alerts warnings" },
  { id:"review-racks", label:"Review Rack Access", description:"Review pharmacy rack assignments", to:"/app/settings", keywords:"rack access staff" },
  { id:"review-user-access", label:"Review User Access", description:"Review staff permissions", to:"/app/settings", keywords:"staff users permissions" },
  { id:"review-shortcuts", label:"Review All Shortcuts", description:"Open the complete shortcut reference", to:"/app/shortcuts", keywords:"shortcut reference keyboard" },
  { id:"calculator-panel", label:"Calculator Panel", description:"Open the pharmacy calculator", to:"/app/calculator", keywords:"calculator" },
  { id:"dashboard-alerts", label:"Dashboard Alerts", description:"Return to the dashboard and review live alerts", to:"/app", keywords:"dashboard alerts" },
  { id:"daily-opening-review", label:"Opening Review", description:"Review stock, messages and operational work at opening", to:"/app/workflows", keywords:"opening checklist morning" },
  { id:"daily-closing-review", label:"Closing Review", description:"Review cash, payables and unresolved work before closing", to:"/app/workflows", keywords:"closing checklist end day" },
  { id:"reorder-workflow", label:"Smart Reorder Workflow", description:"Run the guided low-stock to purchase workflow", to:"/app/workflows", permission:"purchases", keywords:"reorder workflow low stock po" },
  { id:"expiry-workflow", label:"Expiry Review Workflow", description:"Run a guided expiry review and disposition workflow", to:"/app/workflows", permission:"operations", keywords:"expiry workflow writeoff return" },
  { id:"supplier-payment-workflow", label:"Supplier Payment Workflow", description:"Review invoices, balances and supplier payments", to:"/app/workflows", permission:"operations", keywords:"supplier payment payable invoice" },
  { id:"stock-reconciliation-workflow", label:"Stock Reconciliation Workflow", description:"Run a guided batch reconciliation workflow", to:"/app/workflows", permission:"inventory", keywords:"stock reconciliation batch" },
  { id:"customer-review-workflow", label:"Customer Review Workflow", description:"Review customer balances and purchase history", to:"/app/workflows", permission:"customers", keywords:"customer review history balance" },
  { id:"report-review-workflow", label:"Report Review Workflow", description:"Run a guided daily report review", to:"/app/workflows", permission:"reports", keywords:"report review daily" },
  { id:"backup-review", label:"Backup Review", description:"Open backup and data settings", to:"/app/settings", keywords:"backup data restore" },
  { id:"workspace-layout", label:"Workspace Layout", description:"Open workspace settings for navigation layout", to:"/app/settings", keywords:"layout navigation tabs sidebar" },
  { id:"notification-rules", label:"Notification Rules", description:"Configure pharmacy alert preferences", to:"/app/settings", keywords:"notification rules alerts" },
];
