export type AppLanguage={code:string;name:string;nativeName:string;dir?:"ltr"|"rtl"};
export const APP_LANGUAGES:AppLanguage[]=[{code:"en",name:"English",nativeName:"English",dir:"ltr"},{code:"ur",name:"Urdu",nativeName:"اردو",dir:"rtl"},{code:"ar",name:"Arabic",nativeName:"العربية",dir:"rtl"},{code:"hi",name:"Hindi",nativeName:"हिन्दी",dir:"ltr"},{code:"bn",name:"Bengali",nativeName:"বাংলা",dir:"ltr"},{code:"pa",name:"Punjabi",nativeName:"ਪੰਜਾਬੀ",dir:"ltr"},{code:"fa",name:"Persian",nativeName:"فارسی",dir:"rtl"},{code:"tr",name:"Turkish",nativeName:"Türkçe",dir:"ltr"},{code:"id",name:"Indonesian",nativeName:"Bahasa Indonesia",dir:"ltr"},{code:"ms",name:"Malay",nativeName:"Bahasa Melayu",dir:"ltr"},{code:"es",name:"Spanish",nativeName:"Español",dir:"ltr"},{code:"fr",name:"French",nativeName:"Français",dir:"ltr"},{code:"de",name:"German",nativeName:"Deutsch",dir:"ltr"},{code:"it",name:"Italian",nativeName:"Italiano",dir:"ltr"},{code:"pt",name:"Portuguese",nativeName:"Português",dir:"ltr"},{code:"ru",name:"Russian",nativeName:"Русский",dir:"ltr"},{code:"zh",name:"Chinese",nativeName:"中文",dir:"ltr"},{code:"ja",name:"Japanese",nativeName:"日本語",dir:"ltr"},{code:"ko",name:"Korean",nativeName:"한국어",dir:"ltr"},{code:"ps",name:"Pashto",nativeName:"پښتو",dir:"rtl"},{code:"uk",name:"Ukrainian",nativeName:"Українська",dir:"ltr"},{code:"vi",name:"Vietnamese",nativeName:"Tiếng Việt",dir:"ltr"},{code:"th",name:"Thai",nativeName:"ไทย",dir:"ltr"}];
type Dict=Record<string,string>;
const D:Record<string,Dict>={
ur:{Dashboard:"ڈیش بورڈ",Medicines:"ادویات",Inventory:"انوینٹری",Purchases:"خریداری",Customers:"گاہک",Suppliers:"سپلائرز",Reports:"رپورٹس",Settings:"ترتیبات",Messages:"پیغامات",Notifications:"اطلاعات",Search:"تلاش",Save:"محفوظ کریں",Cancel:"منسوخ",Open:"کھولیں",Close:"بند کریں","What's New":"نیا کیا ہے",Help:"مدد","Stock Take":"اسٹاک ٹیک",Racks:"ریکس","Pharmacy Operations":"فارمیسی آپریشنز","Workflow Engine":"ورک فلو انجن","Simple Purchase":"سادہ خریداری","Purchase Cycle":"خریداری سائیکل",Overview:"جائزہ",Reorder:"دوبارہ آرڈر",Returns:"واپسی","New Medicine":"نئی دوا","New Customer":"نیا گاہک","New Supplier":"نیا سپلائر","New Purchase":"نئی خریداری"},
ar:{Dashboard:"لوحة التحكم",Medicines:"الأدوية",Inventory:"المخزون",Purchases:"المشتريات",Customers:"العملاء",Suppliers:"الموردون",Reports:"التقارير",Settings:"الإعدادات",Messages:"الرسائل",Notifications:"الإشعارات",Search:"بحث",Save:"حفظ",Cancel:"إلغاء",Open:"فتح",Close:"إغلاق","What's New":"ما الجديد",Help:"مساعدة","Stock Take":"جرد المخزون",Racks:"الرفوف","Pharmacy Operations":"عمليات الصيدلية","Workflow Engine":"محرك سير العمل","Simple Purchase":"شراء بسيط","Purchase Cycle":"دورة الشراء",Overview:"نظرة عامة",Reorder:"إعادة الطلب",Returns:"المرتجعات","New Medicine":"دواء جديد","New Customer":"عميل جديد","New Supplier":"مورد جديد","New Purchase":"شراء جديد"},
hi:{Dashboard:"डैशबोर्ड",Medicines:"दवाइयाँ",Inventory:"इन्वेंटरी",Purchases:"खरीद",Customers:"ग्राहक",Suppliers:"सप्लायर",Reports:"रिपोर्ट",Settings:"सेटिंग्स",Messages:"संदेश",Notifications:"सूचनाएँ",Search:"खोजें",Save:"सहेजें",Cancel:"रद्द करें",Open:"खोलें",Close:"बंद करें","What's New":"नया क्या है",Help:"मदद","Stock Take":"स्टॉक गणना",Racks:"रैक","Pharmacy Operations":"फार्मेसी संचालन","Workflow Engine":"वर्कफ़्लो इंजन","Simple Purchase":"सरल खरीद","Purchase Cycle":"खरीद चक्र",Overview:"अवलोकन",Reorder:"पुनः ऑर्डर",Returns:"रिटर्न","New Medicine":"नई दवा","New Customer":"नया ग्राहक","New Supplier":"नया सप्लायर","New Purchase":"नई खरीद"},
es:{Dashboard:"Panel",Medicines:"Medicamentos",Inventory:"Inventario",Purchases:"Compras",Customers:"Clientes",Suppliers:"Proveedores",Reports:"Informes",Settings:"Configuración",Messages:"Mensajes",Notifications:"Notificaciones",Search:"Buscar",Save:"Guardar",Cancel:"Cancelar",Open:"Abrir",Close:"Cerrar","What's New":"Novedades",Help:"Ayuda","Stock Take":"Inventario físico",Racks:"Estanterías","Pharmacy Operations":"Operaciones de farmacia","Workflow Engine":"Motor de flujos","Simple Purchase":"Compra simple","Purchase Cycle":"Ciclo de compra",Overview:"Resumen",Reorder:"Reordenar",Returns:"Devoluciones","New Medicine":"Nuevo medicamento","New Customer":"Nuevo cliente","New Supplier":"Nuevo proveedor","New Purchase":"Nueva compra"},
fr:{Dashboard:"Tableau de bord",Medicines:"Médicaments",Inventory:"Inventaire",Purchases:"Achats",Customers:"Clients",Suppliers:"Fournisseurs",Reports:"Rapports",Settings:"Paramètres",Messages:"Messages",Notifications:"Notifications",Search:"Rechercher",Save:"Enregistrer",Cancel:"Annuler",Open:"Ouvrir",Close:"Fermer","What's New":"Nouveautés",Help:"Aide","Stock Take":"Inventaire physique",Racks:"Rayons","Pharmacy Operations":"Opérations de pharmacie","Workflow Engine":"Moteur de workflows","Simple Purchase":"Achat simple","Purchase Cycle":"Cycle d'achat",Overview:"Vue d'ensemble",Reorder:"Réapprovisionnement",Returns:"Retours","New Medicine":"Nouveau médicament","New Customer":"Nouveau client","New Supplier":"Nouveau fournisseur","New Purchase":"Nouvel achat"},
de:{Dashboard:"Dashboard",Medicines:"Medikamente",Inventory:"Inventar",Purchases:"Einkäufe",Customers:"Kunden",Suppliers:"Lieferanten",Reports:"Berichte",Settings:"Einstellungen",Messages:"Nachrichten",Notifications:"Benachrichtigungen",Search:"Suchen",Save:"Speichern",Cancel:"Abbrechen",Open:"Öffnen",Close:"Schließen","What's New":"Neuigkeiten",Help:"Hilfe","Stock Take":"Inventur",Racks:"Regale","Pharmacy Operations":"Apothekenbetrieb","Workflow Engine":"Workflow-Engine","Simple Purchase":"Einfacher Einkauf","Purchase Cycle":"Einkaufszyklus",Overview:"Übersicht",Reorder:"Nachbestellen",Returns:"Retouren","New Medicine":"Neues Medikament","New Customer":"Neuer Kunde","New Supplier":"Neuer Lieferant","New Purchase":"Neuer Einkauf"},
tr:{Dashboard:"Gösterge Paneli",Medicines:"İlaçlar",Inventory:"Stok",Purchases:"Satın Almalar",Customers:"Müşteriler",Suppliers:"Tedarikçiler",Reports:"Raporlar",Settings:"Ayarlar",Messages:"Mesajlar",Notifications:"Bildirimler",Search:"Ara",Save:"Kaydet",Cancel:"İptal",Open:"Aç",Close:"Kapat","What's New":"Yenilikler",Help:"Yardım","Stock Take":"Stok Sayımı",Racks:"Raflar","Pharmacy Operations":"Eczane İşlemleri","Workflow Engine":"İş Akışı Motoru","Simple Purchase":"Basit Satın Alma","Purchase Cycle":"Satın Alma Döngüsü",Overview:"Genel Bakış",Reorder:"Yeniden Sipariş",Returns:"İadeler","New Medicine":"Yeni İlaç","New Customer":"Yeni Müşteri","New Supplier":"Yeni Tedarikçi","New Purchase":"Yeni Satın Alma"},
zh:{Dashboard:"仪表板",Medicines:"药品",Inventory:"库存",Purchases:"采购",Customers:"客户",Suppliers:"供应商",Reports:"报告",Settings:"设置",Messages:"消息",Notifications:"通知",Search:"搜索",Save:"保存",Cancel:"取消",Open:"打开",Close:"关闭","What's New":"最新内容",Help:"帮助","Stock Take":"库存盘点",Racks:"货架","Pharmacy Operations":"药房运营","Workflow Engine":"工作流引擎","Simple Purchase":"简单采购","Purchase Cycle":"采购周期",Overview:"概览",Reorder:"补货",Returns:"退货","New Medicine":"新药品","New Customer":"新客户","New Supplier":"新供应商","New Purchase":"新采购"},
ru:{Dashboard:"Панель",Medicines:"Лекарства",Inventory:"Склад",Purchases:"Закупки",Customers:"Клиенты",Suppliers:"Поставщики",Reports:"Отчёты",Settings:"Настройки",Messages:"Сообщения",Notifications:"Уведомления",Search:"Поиск",Save:"Сохранить",Cancel:"Отмена",Open:"Открыть",Close:"Закрыть","What's New":"Что нового",Help:"Помощь","Stock Take":"Инвентаризация",Racks:"Стеллажи","Pharmacy Operations":"Операции аптеки","Workflow Engine":"Движок процессов","Simple Purchase":"Простая покупка","Purchase Cycle":"Цикл закупки",Overview:"Обзор",Reorder:"Повторный заказ",Returns:"Возвраты","New Medicine":"Новое лекарство","New Customer":"Новый клиент","New Supplier":"Новый поставщик","New Purchase":"Новая покупка"}};
export function getLanguage(){return localStorage.getItem("medicore.language")||"en"}
export function setLanguage(code:string){const lang=APP_LANGUAGES.find(l=>l.code===code)||APP_LANGUAGES[0];localStorage.setItem("medicore.language",lang.code);document.documentElement.lang=lang.code;document.documentElement.dir="ltr";document.documentElement.dataset.languageDir=lang.dir||"ltr";window.dispatchEvent(new CustomEvent("medicore:language-change",{detail:lang.code}))}
export function translateText(text:string,code=getLanguage()){const leading=text.match(/^\s*/)?.[0]||"";const trailing=text.match(/\s*$/)?.[0]||"";const clean=text.trim();const translated=D[code]?.[clean]??clean;return `${leading}${translated}${trailing}`}
const originals=new WeakMap<Text,string>();
export function installLanguageObserver(){const apply=()=>{const code=getLanguage();const lang=APP_LANGUAGES.find(l=>l.code===code)||APP_LANGUAGES[0];document.documentElement.lang=lang.code;document.documentElement.dir="ltr";document.documentElement.dataset.languageDir=lang.dir||"ltr";const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];let n:Node|null;while(n=walker.nextNode())nodes.push(n as Text);for(const node of nodes){if(!originals.has(node))originals.set(node,node.nodeValue||"");const original=originals.get(node)||"";if(!original.trim()||original.length>160)continue;node.nodeValue=code==="en"?original:translateText(original,code)}};const observer=new MutationObserver(()=>{if((window as any).__medicoreLangBusy)return;(window as any).__medicoreLangBusy=true;requestAnimationFrame(()=>{try{apply()}finally{(window as any).__medicoreLangBusy=false}})});observer.observe(document.body,{subtree:true,childList:true});apply();return()=>observer.disconnect()}
