/** Central catalog for pharmacy notification preferences. */
export const NOTIFICATION_TYPES = [
  "messageReceived","messageDelivered","messageRead","medicineAdd","medicineEdit","medicineDelete","medicinePriceChange","medicineMrpChange","medicineStockChange","medicineLowStock","medicineOutOfStock","medicineExpirySoon","medicineExpired","medicineBatchAdd","medicineBatchEdit","medicineBatchDelete","medicineRackChanged","medicineBarcodeChanged","medicineUnitChanged","medicinePackChanged","medicineReorderSuggested","medicineDeadStock","medicineFastMoving","medicineSlowMoving",
  "saleCompleted","forceSale","largeSale","saleCancelled","saleEdited","saleReturned","partialSaleReturn","fullSaleReturn","salePriceChanged","discountApplied","largeDiscount","taxChanged","paymentReceived","paymentPartial","creditSale","cashDrawerOpened","cashDrawerClosed","cashVariance","checkoutStarted","checkoutAbandoned","saleReceiptPrinted","saleReceiptShared","saleWhatsAppShared","saleDuplicateDetected","saleIntegrityWarning",
  "customerAdd","customerEdit","customerDelete","customerPayment","customerCreditLimit","customerBalanceHigh","customerCreditDue","customerCreditOverdue","customerPurchaseMilestone","customerInactive","customerVisitDue","patientHistoryUpdated",
  "purchaseAdd","purchaseEdit","purchaseDelete","purchaseReturned","partialPurchaseReturn","fullPurchaseReturn","purchasePriceChanged","purchaseReceived","purchaseInvoiceCreated","purchaseInvoicePosted","purchaseInvoiceOverdue","purchaseInvoicePaid","supplierAdd","supplierEdit","supplierDelete","supplierPayment","supplierBalanceHigh","supplierInvoiceDuplicate","supplierCreditLimit","supplierPayableDue","supplierPayableOverdue","grnCreated","grnUpdated","grnPosted","grnRejected","grnMismatch",
  "categoryAdd","categoryEdit","categoryDelete","inventoryBatchAdd","inventoryBatchLowStock","inventoryBatchExpired","inventoryAdjustment","stockTransfer","stockTransferRequested","stockTransferApproved","stockTransferCompleted","stockTransferRejected","stockCorrection","negativeStockPrevented","stockReconciliationStarted","stockReconciliationCompleted","stockReconciliationVariance","stockTakeCreated","stockTakeSubmitted","stockTakeApproved","stockTakeRejected","stockTakeOverdue","expiryWriteOffCreated","expiryWriteOffApproved","returnToSupplierCreated","returnToSupplierCompleted",
  "prescriptionAdd","prescriptionEdit","prescriptionDelete","prescriptionDueSoon","prescriptionDueToday","prescriptionVisitLoaded","prescriptionMedicineOutOfStock","prescriptionVisibilityChanged","prescriptionRefillDue","prescriptionRefillCompleted",
  "backupCreated","backupFailed","backupRestored","backupReminder","loginSuccess","loginFailed","userCreated","userEdited","userDeleted","permissionChanged","duplicateUsernameBlocked","serverConnected","serverDisconnected","syncConflict","syncCompleted","dataSaveFailed","dataRestored","printerFailed","printCompleted","returnRejected","mrpValidationFailed","checkoutPriceChanged","settingsChanged","pinAdded","pinRemoved","reportExported","reportPrinted","reportScheduled","reportExportFailed","workflowStarted","workflowStepCompleted","workflowStepBlocked","workflowCompleted","workflowReset","workflowAssigned","workflowOverdue","workflowAuditCreated","intentCreated","intentResolved","intentDismissed","intentEscalated","macroCreated","macroUpdated","macroDeleted","macroStarted","macroCompleted","macroStepCompleted","commandExecuted","commandFailed","shortcutTriggered","shortcutConflict","rackCreated","rackEdited","rackDeleted","rackAccessChanged","rackAccessDenied","rackMissingOnSave","notificationDigestReady","notificationPreferenceChanged","dailyOpeningReminder","dailyClosingReminder","cashClosingReminder","expiryDigestReady","lowStockDigestReady","payablesDigestReady",
] as const;

export type NotificationType = typeof NOTIFICATION_TYPES[number];

/** Safety, stock, messaging and workflow failures are enabled by default; informational events remain opt-in. */
export const DEFAULT_NOTIFICATION_PREFERENCES: Record<NotificationType, boolean> = Object.fromEntries(
  NOTIFICATION_TYPES.map((type) => [type, [
    "messageReceived","messageDelivered","medicineLowStock","medicineOutOfStock","medicineExpirySoon","medicineExpired","medicineReorderSuggested","medicineDeadStock","saleReturned","paymentPartial","creditSale","cashVariance","saleIntegrityWarning","customerBalanceHigh","customerCreditOverdue","purchaseInvoiceOverdue","supplierBalanceHigh","supplierPayableOverdue","grnMismatch","inventoryBatchExpired","negativeStockPrevented","stockReconciliationVariance","stockTakeOverdue","expiryWriteOffCreated","returnToSupplierCreated","prescriptionDueSoon","prescriptionDueToday","prescriptionMedicineOutOfStock","backupFailed","backupRestored","backupReminder","loginFailed","duplicateUsernameBlocked","syncConflict","dataSaveFailed","printerFailed","returnRejected","mrpValidationFailed","checkoutPriceChanged","workflowStepBlocked","workflowOverdue","intentEscalated","macroFailed","shortcutConflict","rackAccessDenied","rackMissingOnSave","expiryDigestReady","lowStockDigestReady","payablesDigestReady","dailyClosingReminder","cashClosingReminder",
  ].includes(type)])
) as Record<NotificationType, boolean>;

export const NOTIFICATION_LABELS: Record<NotificationType, string> = Object.fromEntries(
  NOTIFICATION_TYPES.map((type) => [type, type.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase())])
) as Record<NotificationType, string>;
