/** Multi-user accounts + granular permissions. */
export type UserRole = "admin" | "user";
export interface UserPermissions {
  sales: boolean; bills: boolean; medicines: boolean; inventory: boolean; purchases: boolean; reports: boolean; suppliers: boolean; categories: boolean; customers: boolean; operations: boolean; notifications: boolean; prescriptions?: boolean; stocktake?: boolean; patients?: boolean; messages?: boolean; racks?: boolean; racksAdd?: boolean; rackSell?: boolean; rackStocktake?: boolean;
  applyDiscount: boolean; changeTax: boolean; forceSale: boolean; changeCheckoutPrice?: boolean; pinPanel?: boolean; viewPinPanel?: boolean; viewNotifications?: boolean; messagesToAdmin?: boolean; messagesToUsers?: boolean;
  prescriptionsAdd?: boolean; prescriptionsEdit?: boolean; prescriptionsDelete?: boolean; prescriptionsPrint?: boolean; prescriptionsLoadToSale?: boolean;
  operationsBarcode?: boolean; operationsBatches?: boolean; operationsReturns?: boolean; operationsCustomerLedger?: boolean; operationsSupplierLedger?: boolean;
  medicinesAdd?: boolean; medicinesEdit?: boolean; medicinesDelete?: boolean; customersAdd?: boolean; customersEdit?: boolean; customersDelete?: boolean; purchasesAdd?: boolean; purchasesEdit?: boolean; purchasesDelete?: boolean; suppliersAdd?: boolean; suppliersEdit?: boolean; suppliersDelete?: boolean; categoriesAdd?: boolean; categoriesEdit?: boolean; categoriesDelete?: boolean; reportsExport?: boolean; reportsPrint?: boolean;
}
export type CounterId = "totalMedicines" | "lowStock" | "expired" | "todayRevenue" | "todayProfit" | "monthRevenue" | "customers" | "suppliers" | "salesTrend" | "mostSold";
export const ALL_COUNTERS: { id: CounterId; label: string }[] = [
  { id: "totalMedicines", label: "Total Medicines" }, { id: "lowStock", label: "Low Stock" }, { id: "expired", label: "Expired" }, { id: "todayRevenue", label: "Today's Sales" }, { id: "todayProfit", label: "Today's Profit" }, { id: "monthRevenue", label: "Monthly Sales" }, { id: "customers", label: "Customers" }, { id: "suppliers", label: "Suppliers" }, { id: "salesTrend", label: "Sales trend chart" }, { id: "mostSold", label: "Most sold panel" },
];
export type RoleTemplate = "seller" | "custom" | "manager";
export const ROLE_TEMPLATE_LABELS: Record<RoleTemplate, string> = { seller: "Seller — POS + Bills + Medicines", custom: "Custom — pick exact permissions", manager: "Manager — every panel except Settings" };
export interface StoredUser { id: string; username: string; role: UserRole; saltHex: string; hashHex: string; permissions: UserPermissions; allowedRackNames?: string[]; dashboardVisibility?: Partial<Record<CounterId, boolean>>; maxDiscount?: number; roleTemplate?: RoleTemplate; }
const fullCrud = { medicinesAdd: true, medicinesEdit: true, medicinesDelete: true, customersAdd: true, customersEdit: true, customersDelete: true, purchasesAdd: true, purchasesEdit: true, purchasesDelete: true, suppliersAdd: true, suppliersEdit: true, suppliersDelete: true, categoriesAdd: true, categoriesEdit: true, categoriesDelete: true, reportsExport: true, reportsPrint: true, operationsBarcode: true, operationsBatches: true, operationsReturns: true, operationsCustomerLedger: true, operationsSupplierLedger: true, prescriptionsAdd: true, prescriptionsEdit: true, prescriptionsDelete: true, prescriptionsPrint: true, prescriptionsLoadToSale: true };
const noCrud = { medicinesAdd: false, medicinesEdit: false, medicinesDelete: false, customersAdd: false, customersEdit: false, customersDelete: false, purchasesAdd: false, purchasesEdit: false, purchasesDelete: false, suppliersAdd: false, suppliersEdit: false, suppliersDelete: false, categoriesAdd: false, categoriesEdit: false, categoriesDelete: false, reportsExport: false, reportsPrint: false, operationsBarcode: false, operationsBatches: false, operationsReturns: false, operationsCustomerLedger: false, operationsSupplierLedger: false, prescriptionsAdd: false, prescriptionsEdit: false, prescriptionsDelete: false, prescriptionsPrint: false, prescriptionsLoadToSale: false };
export function permissionsForTemplate(template: RoleTemplate): UserPermissions {
  if (template === "manager") return { sales: true, bills: true, medicines: true, inventory: true, stocktake: true, purchases: true, reports: true, suppliers: true, categories: true, customers: true, patients: true, racks: true, racksAdd: true, rackSell: true, rackStocktake: true, operations: true, notifications: true, prescriptions: true, messages: true, messagesToAdmin: true, messagesToUsers: true, applyDiscount: true, changeTax: true, forceSale: true, changeCheckoutPrice: true, pinPanel: true, viewPinPanel: true, viewNotifications: true, ...fullCrud };
  if (template === "seller") return { sales: true, bills: true, medicines: true, inventory: false, stocktake: false, purchases: false, reports: false, suppliers: false, categories: false, customers: false, patients: false, racks: true, racksAdd: false, rackSell: true, rackStocktake: false, operations: true, notifications: false, prescriptions: false, messages: true, messagesToAdmin: true, messagesToUsers: false, applyDiscount: true, changeTax: false, forceSale: false, changeCheckoutPrice: true, pinPanel: false, viewPinPanel: false, viewNotifications: false, ...noCrud, operationsBarcode: true, operationsBatches: false, operationsReturns: false, operationsCustomerLedger: false, operationsSupplierLedger: false };
  return defaultPermissions("user");
}
export function defaultPermissions(role: UserRole): UserPermissions {
  if (role === "admin") return { sales: true, bills: true, medicines: true, inventory: true, stocktake: true, purchases: true, reports: true, suppliers: true, categories: true, customers: true, patients: true, racks: true, racksAdd: true, rackSell: true, rackStocktake: true, operations: true, notifications: true, prescriptions: true, messages: true, messagesToAdmin: true, messagesToUsers: true, applyDiscount: true, changeTax: true, forceSale: true, changeCheckoutPrice: true, pinPanel: true, viewPinPanel: true, viewNotifications: true, ...fullCrud };
  return { sales: true, bills: true, medicines: false, inventory: false, stocktake: false, purchases: false, reports: false, suppliers: false, categories: false, customers: false, patients: false, racks: false, racksAdd: false, rackSell: false, rackStocktake: false, operations: false, notifications: false, prescriptions: false, messages: true, messagesToAdmin: true, messagesToUsers: false, applyDiscount: false, changeTax: false, forceSale: false, changeCheckoutPrice: false, pinPanel: false, viewPinPanel: false, viewNotifications: false, ...noCrud };
}
export function isCounterVisible(u: StoredUser | null, id: CounterId): boolean { if (!u || u.role === "admin") return true; return u.dashboardVisibility?.[id] !== false; }
