/** Canonical in-memory project schema. */
export interface InventoryBatch { id: string; medicineId: string; sourceKey?: string; purchaseId?: string; purchaseItemIndex?: number; batchNumber?: string; barcode?: string; quantity: number; initialQuantity?: number; purchasePrice: number; expiryDate?: string; manufactureDate?: string; receivedDate?: string; }
export interface SaleReturn { id: string; saleId: string; date: string; customerId?: string; items: { medicineId: string; quantity: number; salePrice: number; batchId?: string }[]; reason?: string; createdBy?: string; }
export interface PurchaseReturn { id: string; purchaseId: string; supplierId?: string; date: string; items: { medicineId: string; quantity: number; purchasePrice: number; batchId?: string }[]; reason?: string; createdBy?: string; }
export interface CustomerLedgerEntry { id: string; customerId: string; date: string; type: "sale" | "payment" | "return" | "adjustment"; amount: number; reference?: string; note?: string; }
export interface SupplierLedgerEntry { id: string; supplierId: string; date: string; type: "purchase" | "payment" | "return" | "adjustment"; amount: number; reference?: string; note?: string; }
export type PurchaseOrderStatus = "draft" | "ordered" | "partial" | "received" | "cancelled";
export type GoodsReceiptStatus = "draft" | "posted" | "cancelled";
export type PurchaseInvoiceStatus = "unpaid" | "partial" | "paid" | "cancelled";
export interface PurchaseOrderLine { medicineId: string; quantityOrdered: number; unitCost: number; bonusQuantity?: number; }
export interface PurchaseOrder { id: string; supplierId: string; poNumber: string; date: string; expectedDate?: string; status: PurchaseOrderStatus; lines: PurchaseOrderLine[]; notes?: string; }
export interface GoodsReceiptLine { medicineId: string; quantityReceived: number; bonusQuantity?: number; batchNumber: string; expiryDate: string; unitCost: number; purchaseOrderLineId?: string; }
export interface GoodsReceipt { id: string; supplierId: string; purchaseOrderId?: string; grnNumber: string; receivedAt: string; status: GoodsReceiptStatus; lines: GoodsReceiptLine[]; notes?: string; }
export interface PurchaseInvoice { id: string; supplierId: string; invoiceNumber: string; invoiceDate: string; dueDate?: string; purchaseOrderId?: string; goodsReceiptIds: string[]; subtotal: number; discount: number; tax: number; total: number; paid: number; balance: number; status: PurchaseInvoiceStatus; notes?: string; }
export interface SupplierPaymentAllocation { invoiceId: string; amount: number; }
export interface SupplierPayment { id: string; supplierId: string; paidAt: string; amount: number; method: "cash" | "card" | "bank" | "online" | "other"; reference?: string; allocations: SupplierPaymentAllocation[]; notes?: string; }
export type PrescriptionVisibility = "admin" | "all" | "selected"; export type PrescriptionRepeatUnit = "day" | "week" | "month" | "year";
export interface PrescriptionLine { medicineId: string; quantity: number; dosage?: string; frequency?: string; duration?: string; instructions?: string; }
export interface Prescription { id: string; date: string; patientName: string; patientPhone?: string; doctorName?: string; diagnosis?: string; notes?: string; items: PrescriptionLine[]; createdBy?: string; visibility: PrescriptionVisibility; allowedUserIds?: string[]; nextVisitDate?: string; repeatEvery?: number; repeatUnit?: PrescriptionRepeatUnit; notifyBeforeDays?: number; }
export interface FbrSettings { enabled: boolean; ntn?: string; strn?: string; posId?: string; invoicePrefix: string; nextInvoiceNumber: number; }
export interface PharmacySettings {
  pharmacyName: string; ownerName: string; phone: string; email: string; address: string; taxPercent: number; maxDiscount?: number; singleSessionOnly?: boolean;
  defaultSearchBy?: "name" | "generic" | "company" | "all"; notifyOnDeleteMedicine?: boolean; notifyOnAddMedicine?: boolean; notifyOnAddCustomer?: boolean; notifyOnLargeSale?: boolean; notifyOnForceSale?: boolean; largeSaleThreshold?: number; invoiceCounter?: number; currency: string; currencySymbol: string;
  receiptFooter: string; receiptLogoDataUrl?: string; billFooter1: string; billFooter2: string; autoSaveEnabled: boolean; autoSaveIntervalMinutes: 1 | 2 | 5 | 10 | 15; theme: "light" | "dark"; passwordProtected: boolean; tabShortcutsEnabled?: boolean; keyboardNavigationEnabled?: boolean; tabShortcuts?: Record<string, number>; tabHotkeys?: Record<string, string>; actionHotkeys?: Record<string, string>; tabOrder?: string[]; tabGroups?: Record<string, string>; tabRenames?: Record<string, string>; groupRenames?: Record<string, string>; calculatorEnabled?: boolean; dashboardHidden?: string[]; trendMetric?: "sales" | "profit" | "purchases"; trendRange?: "week" | "month" | "all"; trendChartType?: "bar" | "line"; hiddenQuickActions?: string[]; pinnedItems?: PinnedItem[]; pinPanelHidden?: boolean; pinPanelMinimized?: boolean; sidebarWidth?: number; topbarHeight?: number; pinBarHeight?: number; autoBackupEnabled?: boolean; autoBackupIntervalHours?: number; autoBackupFolder?: string; lastAutoBackupAt?: number; backupPasswordEnabled?: boolean; backupPassword?: string; allowCheckoutPriceChange?: boolean;
  notificationPreferences?: Record<string, boolean>; notificationRetentionDays?: number; inventoryBatches?: InventoryBatch[]; inventoryBatchMigrationVersion?: number; saleReturns?: SaleReturn[]; purchaseReturns?: PurchaseReturn[]; customerLedger?: CustomerLedgerEntry[]; supplierLedger?: SupplierLedgerEntry[]; prescriptions?: Prescription[]; expenses?: Expense[]; cashDrawer?: CashDrawerSession;
  purchaseOrders?: PurchaseOrder[]; goodsReceipts?: GoodsReceipt[]; purchaseInvoices?: PurchaseInvoice[]; supplierPayments?: SupplierPayment[];
  fbr?: FbrSettings;
  stockTakes?: StockTake[]; inventoryDispositions?: InventoryDisposition[];
}
export type PinKind = "nav" | "action" | "cmd" | "counter"; export interface PinnedItem { id: string; label: string; kind: PinKind; to?: string; }
export interface Category { id: string; name: string; description?: string; }
export interface Supplier { id: string; name: string; phone?: string; email?: string; address?: string; company?: string; balance: number; }
export interface Customer { id: string; name: string; phone?: string; email?: string; address?: string; balance: number; loyaltyPoints: number; specialDiscountPercent?: number; priceTier?: "retail" | "wholesale"; }
export interface MedicineUnitOption { id: string; label: string; factor: number; price: number; }
export interface MedicineUnitConfig { baseUnit: string; options: MedicineUnitOption[]; }
export interface PriceTier { minQuantity: number; price: number; label?: string; }
export interface Expense { id: string; date: string; category: string; description?: string; amount: number; paymentMethod: "cash" | "card" | "online"; createdBy?: string; }
export interface CashDrawerSession { id: string; openedAt: string; openingCash: number; closedAt?: string; closingCash?: number; expectedCash?: number; difference?: number; closedBy?: string; }
export interface Medicine { id: string; name: string; genericName?: string; company?: string; categoryId?: string; batchNumber?: string; barcode?: string; qrCode?: string; purchasePrice: number; salePrice: number; wholesalePrice?: number; priceTiers?: PriceTier[]; mrp: number; stockQuantity: number; minimumStock: number; expiryDate?: string; manufactureDate?: string; rackNumber?: string; supplierId?: string; description?: string; searchAliases?: string[]; pinOrder?: "first" | "last"; unitConfig?: MedicineUnitConfig; strength?: string; dosageForm?: string; packSize?: number; packUnit?: string; registrationNumber?: string; prescriptionRequired?: boolean; controlledDrug?: boolean; storageCondition?: string; }
export interface PurchaseItem { medicineId: string; quantity: number; purchasePrice: number; batchNumber?: string; expiryDate?: string; }
export interface Purchase { id: string; supplierId: string; invoiceNumber: string; purchaseDate: string; receivedDate?: string; items: PurchaseItem[]; taxPercent: number; discount: number; notes?: string; status?: "received" | "partial" | "cancelled"; purchaseOrderId?: string; }
export type PaymentMethod = "cash" | "card" | "online" | "credit" | "mixed";
export interface SaleItem { medicineId: string; quantity: number; salePrice: number; discountPercent: number; costPriceAtSale?: number; batchId?: string; batchAllocations?: { batchId: string; quantity: number; costPrice: number }[]; unitLabel?: string; unitQuantity?: number; unitFactor?: number; forcedSale?: boolean; }
export interface SalePayment { method: "cash" | "card" | "online" | "credit"; amount: number; reference?: string; }
export interface Sale { id: string; invoiceNumber: string; date: string; customerId?: string; remark?: string; items: SaleItem[]; discount: number; taxPercent: number; payments: SalePayment[]; status: "completed" | "cancelled" | "returned"; notes?: string; createdBy?: string; reprints?: string[]; }
export interface StockAdjustment { id: string; medicineId: string; date: string; delta: number; reason: string; kind?: "stocktake" | "writeoff" | "manual"; createdBy?: string; batchId?: string; }
export interface StockTakeLine { medicineId: string; batchId: string; systemQuantity: number; countedQuantity: number; variance: number; unitCost: number; reason?: string; }
export interface StockTake { id: string; number: string; startedAt: string; completedAt?: string; status: "draft" | "posted" | "cancelled"; lines: StockTakeLine[]; notes?: string; createdBy?: string; postedBy?: string; }
export type InventoryDispositionKind = "expired" | "damaged" | "supplier_return";
export interface InventoryDispositionLine { medicineId: string; batchId: string; quantity: number; unitCost: number; }
export interface InventoryDisposition { id: string; number: string; kind: InventoryDispositionKind; date: string; status: "posted" | "cancelled"; supplierId?: string; lines: InventoryDispositionLine[]; reason?: string; createdBy?: string; }
export interface ProjectData { meta: { id: string; name: string; createdAt: string; updatedAt: string; schemaVersion: number }; settings: PharmacySettings; categories: Category[]; suppliers: Supplier[]; customers: Customer[]; medicines: Medicine[]; purchases: Purchase[]; sales: Sale[]; stockAdjustments: StockAdjustment[]; }
export const SCHEMA_VERSION = 8;
export function createEmptyProject(name: string, passwordProtected: boolean): ProjectData { const now = new Date().toISOString(); return { meta: { id: crypto.randomUUID(), name, createdAt: now, updatedAt: now, schemaVersion: SCHEMA_VERSION }, settings: { pharmacyName: name, ownerName: "", phone: "", email: "", address: "", taxPercent: 0, maxDiscount: 0, currency: "PKR", currencySymbol: "₨", receiptFooter: "Thank you for your purchase", billFooter1: "Thanks for purchasing", billFooter2: "Please check & verify your medicines. Medicines will be returned within 15 days. Fridge items are not returnable. Pharmacy is not responsible after this period.", autoSaveEnabled: true, autoBackupEnabled: false, autoBackupIntervalHours: 24, autoSaveIntervalMinutes: 5, theme: "light", passwordProtected, allowCheckoutPriceChange: true, notifyOnForceSale: true, keyboardNavigationEnabled: true, notificationPreferences: {}, notificationRetentionDays: 90, inventoryBatches: [], inventoryBatchMigrationVersion: 0, saleReturns: [], purchaseReturns: [], customerLedger: [], supplierLedger: [], prescriptions: [], expenses: [], cashDrawer: undefined, purchaseOrders: [], goodsReceipts: [], purchaseInvoices: [], supplierPayments: [], fbr: { enabled: false, invoicePrefix: "INV-", nextInvoiceNumber: 1 }, stockTakes: [], inventoryDispositions: [] }, categories: [], suppliers: [], customers: [], medicines: [], purchases: [], sales: [], stockAdjustments: [] }; }