import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Barcode, CalendarClock, RotateCcw, Users, Truck, Search, Plus, ArrowDownLeft, ArrowUpRight } from "lucide-react";
import { toast } from "sonner";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
import { PermissionGate } from "@/components/PermissionGate";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { uid, money } from "@/lib/format";
import type { InventoryBatch, PurchaseReturn, SaleReturn, MedicineUnitOption } from "@/domain/schema";
import { recordPurchaseReturn, recordSaleReturn } from "@/lib/transaction-engine";
import { financeSummary, expectedCash } from "@/lib/finance-engine";
import { UnitManager } from "@/components/operations/UnitManager";
import { FinanceManager } from "@/components/operations/FinanceManager";
import { PharmacyControls } from "@/components/PharmacyControls";
import { P2PharmacyOperations } from "@/components/P2PharmacyOperations";

export const Route = createFileRoute("/app/operations")({ component: () => <PermissionGate perm="operations"><OperationsPage /></PermissionGate> });

function OperationsPage() {
  const data = useProjectStore((s) => s.data!); const mutate = useProjectStore((s) => s.mutate); const user = useSession((s) => s.user); const sym = data.settings.currencySymbol || "$";
  const [scan,setScan]=useState(""); const [tab,setTab]=useState("barcode"); const [selectedMedicine,setSelectedMedicine]=useState(data.medicines[0]?.id??""); const [batchQty,setBatchQty]=useState(0); const [batchPrice,setBatchPrice]=useState(0); const [batchNumber,setBatchNumber]=useState(""); const [batchExpiry,setBatchExpiry]=useState(""); const [saleId,setSaleId]=useState(""); const [saleReturnQty,setSaleReturnQty]=useState<Record<string,number>>({}); const [purchaseId,setPurchaseId]=useState(""); const [purchaseReturnQty,setPurchaseReturnQty]=useState<Record<string,number>>({}); const [customerId,setCustomerId]=useState(data.customers[0]?.id??""); const [supplierId,setSupplierId]=useState(data.suppliers[0]?.id??""); const [paymentAmount,setPaymentAmount]=useState(0); const [paymentNote,setPaymentNote]=useState("");
  const p=user?.permissions; const canBarcode=user?.role==="admin"||p?.operationsBarcode===true; const canBatches=user?.role==="admin"||p?.operationsBatches===true; const canReturns=user?.role==="admin"||p?.operationsReturns===true; const canCustomers=user?.role==="admin"||p?.operationsCustomerLedger===true; const canSuppliers=user?.role==="admin"||p?.operationsSupplierLedger===true;
  const firstTab=canBarcode?"barcode":canBatches?"batches":canReturns?"returns":canCustomers?"customers":"suppliers";
  const activeTab=["barcode","batches","returns","customers","suppliers"].includes(tab)&&({barcode:canBarcode,batches:canBatches,returns:canReturns,customers:canCustomers,suppliers:canSuppliers} as Record<string,boolean>)[tab]?tab:firstTab;
  const scanned=useMemo(()=>{const q=scan.trim().toLowerCase();if(!q)return [];return data.medicines.filter((m)=>(m.barcode??"").toLowerCase()===q||(m.barcode??"").toLowerCase().includes(q)).slice(0,10);},[data.medicines,scan]);
  const batches=data.settings.inventoryBatches??[];
  const expiring=useMemo(()=>{const now=Date.now();return batches.filter(b=>b.expiryDate&&new Date(b.expiryDate).getTime()>=now).map(b=>({...b,days:Math.ceil((new Date(b.expiryDate!).getTime()-now)/86400000),medicine:data.medicines.find(m=>m.id===b.medicineId)})).filter(b=>b.medicine).sort((a,b)=>new Date(a.expiryDate!).getTime()-new Date(b.expiryDate!).getTime());},[batches,data.medicines]);
  const fefo=[...batches].filter(b=>b.quantity>0).sort((a,b)=>{const ae=a.expiryDate?new Date(a.expiryDate).getTime():Number.MAX_SAFE_INTEGER;const be=b.expiryDate?new Date(b.expiryDate).getTime():Number.MAX_SAFE_INTEGER;return ae-be;}).slice(0,20);
  const selectedSale=data.sales.find(s=>s.id===saleId); const selectedPurchase=data.purchases.find(p=>p.id===purchaseId);
  function addBatch(){const m=data.medicines.find(x=>x.id===selectedMedicine);if(!m||batchQty<=0)return toast.error("Select a medicine and enter a quantity");const batch:InventoryBatch={id:uid("batch_"),medicineId:m.id,batchNumber:batchNumber.trim()||m.batchNumber,barcode:m.barcode,quantity:batchQty,purchasePrice:batchPrice||m.purchasePrice,expiryDate:batchExpiry||m.expiryDate,receivedDate:new Date().toISOString()};mutate(d=>{d.settings.inventoryBatches=[...(d.settings.inventoryBatches??[]),batch];const med=d.medicines.find(x=>x.id===m.id);if(med)med.stockQuantity+=batch.quantity;});setBatchQty(0);setBatchNumber("");setBatchExpiry("");toast.success(`Batch ${batch.batchNumber||"added"}`);}
  function makeSaleReturn(){if(!selectedSale)return toast.error("Select a sale");try{mutate(d=>{recordSaleReturn(d,selectedSale.id,saleReturnQty,"Customer return",user?.username)});toast.success("Sale return recorded and stock restored");setSaleReturnQty({});}catch(e){toast.error(e instanceof Error?e.message:"Sale return failed")}}
  function makePurchaseReturn(){if(!selectedPurchase)return toast.error("Select a purchase");try{mutate(d=>{recordPurchaseReturn(d,selectedPurchase.id,purchaseReturnQty,"Supplier return",user?.username)});toast.success("Purchase return recorded and batch stock reduced");setPurchaseReturnQty({});}catch(e){toast.error(e instanceof Error?e.message:"Purchase return failed")}}
  const customerRows=data.customers.map(c=>{const sales=data.sales.filter(s=>s.customerId===c.id&&s.status==="completed").reduce((n,s)=>n+s.items.reduce((a,i)=>a+i.salePrice*i.quantity,0)-s.discount,0);const returns=(data.settings.saleReturns??[]).filter(r=>r.customerId===c.id).reduce((n,r)=>n+r.items.reduce((a,i)=>a+i.salePrice*i.quantity,0),0);const payments=(data.settings.customerLedger??[]).filter(e=>e.customerId===c.id&&e.type==="payment").reduce((n,e)=>n+e.amount,0);return {...c,due:Math.max(0,sales-returns-payments)};});
  const supplierRows=data.suppliers.map(s=>{const purchases=data.purchases.filter(p=>p.supplierId===s.id).reduce((n,p)=>n+p.items.reduce((a,i)=>a+i.purchasePrice*i.quantity,0)-p.discount,0);const returns=(data.settings.purchaseReturns??[]).filter(r=>r.supplierId===s.id).reduce((n,r)=>n+r.items.reduce((a,i)=>a+i.purchasePrice*i.quantity,0),0);const payments=(data.settings.supplierLedger??[]).filter(e=>e.supplierId===s.id&&e.type==="payment").reduce((n,e)=>n+e.amount,0);return {...s,due:Math.max(0,purchases-returns-payments)};});
  function recordCustomerPayment(){if(!customerId||paymentAmount<=0)return toast.error("Select a customer and enter payment");mutate(d=>{d.settings.customerLedger=[...(d.settings.customerLedger??[]),{id:uid("cl_"),customerId,date:new Date().toISOString(),type:"payment",amount:paymentAmount,note:paymentNote||undefined,createdBy:user?.username} as any];const c=d.customers.find(x=>x.id===customerId);if(c)c.balance=Math.max(0,(c.balance??0)-paymentAmount);});toast.success("Customer payment recorded");setPaymentAmount(0);setPaymentNote("");}
  function recordSupplierPayment(){if(!supplierId||paymentAmount<=0)return toast.error("Select a supplier and enter payment");mutate(d=>{d.settings.supplierLedger=[...(d.settings.supplierLedger??[]),{id:uid("sl_"),supplierId,date:new Date().toISOString(),type:"payment",amount:paymentAmount,note:paymentNote||undefined,createdBy:user?.username} as any];const s=d.suppliers.find(x=>x.id===supplierId);if(s)s.balance=Math.max(0,(s.balance??0)-paymentAmount);});toast.success("Supplier payment recorded");setPaymentAmount(0);setPaymentNote("");}
  return <div className="mx-auto max-w-7xl p-6 md:p-8"><div className="mb-6"><p className="text-xs uppercase tracking-widest text-muted-foreground">Pharmacy operations</p><h1 className="font-display text-3xl font-bold">Barcode, Batches, Returns & Ledgers</h1><p className="mt-1 text-sm text-muted-foreground">Use the operation tabs your account is allowed to access.</p></div><Tabs value={activeTab} onValueChange={setTab}><TabsList className="grid w-full grid-cols-9">
    {canBarcode&&<TabsTrigger value="barcode"><Barcode className="mr-1 h-4 w-4"/>Barcode</TabsTrigger>}{canBatches&&<TabsTrigger value="batches"><CalendarClock className="mr-1 h-4 w-4"/>Batch + FEFO</TabsTrigger>}{canReturns&&<TabsTrigger value="returns"><RotateCcw className="mr-1 h-4 w-4"/>Returns</TabsTrigger>}{canCustomers&&<TabsTrigger value="customers"><Users className="mr-1 h-4 w-4"/>Customer Ledger</TabsTrigger>}{canSuppliers&&<TabsTrigger value="suppliers"><Truck className="mr-1 h-4 w-4"/>Supplier Ledger</TabsTrigger>}<TabsTrigger value="units">Units</TabsTrigger><TabsTrigger value="finance">Finance</TabsTrigger><TabsTrigger value="controls">P1 Controls</TabsTrigger><TabsTrigger value="p2">P2 Operations</TabsTrigger>
  </TabsList>
  {canBarcode&&<TabsContent value="barcode" className="mt-4"><div className="grid gap-4 lg:grid-cols-2"><div className="surface-card p-5"><h2 className="font-display font-semibold">Scan barcode</h2><p className="mt-1 text-xs text-muted-foreground">USB barcode scanners work as keyboard input. Scan and press Enter.</p><div className="relative mt-4"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input autoFocus value={scan} onChange={e=>setScan(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&scanned[0]){setSelectedMedicine(scanned[0].id);setTab("batches");}}} placeholder="Scan barcode…" className="h-11 pl-9"/></div>{scanned.map(m=><button key={m.id} onClick={()=>{setSelectedMedicine(m.id);setTab("batches");}} className="mt-2 flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-muted"><span><b>{m.name}</b><span className="ml-2 text-xs text-muted-foreground">{m.genericName||m.company||""}</span></span><span className="text-xs text-muted-foreground">{m.barcode} · Stock {m.stockQuantity}</span></button>)}</div><div className="surface-card p-5"><h2 className="font-display font-semibold">Barcode-ready inventory</h2><div className="mt-3 max-h-80 overflow-auto divide-y">{data.medicines.filter(m=>m.barcode).slice(0,100).map(m=><div key={m.id} className="flex items-center justify-between py-2 text-sm"><span>{m.name}</span><span className="font-mono text-xs text-muted-foreground">{m.barcode}</span></div>)}</div></div></div></TabsContent>}
  {canBatches&&<TabsContent value="batches" className="mt-4"><div className="grid gap-4 lg:grid-cols-2"><div className="surface-card p-5"><h2 className="font-display font-semibold">Add inventory batch</h2><div className="mt-4 grid gap-3"><div><Label>Medicine</Label><Select value={selectedMedicine} onValueChange={setSelectedMedicine}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{data.medicines.slice(0,500).map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div><Label>Batch number</Label><Input value={batchNumber} onChange={e=>setBatchNumber(e.target.value)}/></div><div><Label>Quantity</Label><Input type="number" value={batchQty||""} onChange={e=>setBatchQty(Number(e.target.value))}/></div><div><Label>Purchase cost</Label><Input type="number" value={batchPrice||""} onChange={e=>setBatchPrice(Number(e.target.value))}/></div><div><Label>Expiry</Label><Input type="date" value={batchExpiry} onChange={e=>setBatchExpiry(e.target.value)}/></div></div><Button onClick={addBatch}><Plus className="mr-2 h-4 w-4"/>Add batch</Button></div></div><div className="surface-card p-5"><h2 className="font-display font-semibold">FEFO / expiry queue</h2><p className="text-xs text-muted-foreground">Earliest expiry is listed first.</p><div className="mt-3 max-h-96 overflow-auto divide-y">{fefo.map(b=><div key={b.id} className="py-2 text-sm"><div className="flex justify-between"><span>{data.medicines.find(m=>m.id===b.medicineId)?.name||"—"}</span><span>Qty {b.quantity}</span></div><div className="text-xs text-muted-foreground">Batch {b.batchNumber||"—"} · {b.expiryDate?`Expiry ${b.expiryDate}`:"No expiry"}</div></div>)}</div><div className="mt-4 rounded-lg border p-3"><b className="text-sm">Expiring soon</b><div className="mt-2 space-y-1 text-xs">{expiring.slice(0,8).map(b=><div key={b.id} className="flex justify-between"><span>{b.medicine?.name} · {b.batchNumber||"—"}</span><span className={b.days<=30?"text-destructive":"text-muted-foreground"}>{b.days} days</span></div>)}</div></div></div></div></TabsContent>}
  <TabsContent value="units" className="mt-4"><UnitManager /></TabsContent><TabsContent value="finance" className="mt-4"><FinanceManager /></TabsContent><TabsContent value="controls" className="mt-4"><PharmacyControls /></TabsContent><TabsContent value="p2" className="mt-4"><P2PharmacyOperations /></TabsContent>{canReturns&&<TabsContent value="returns" className="mt-4"><div className="grid gap-4 lg:grid-cols-2"><div className="surface-card p-5"><h2 className="font-display font-semibold">Sales return</h2><Select value={saleId} onValueChange={setSaleId}><SelectTrigger className="mt-3"><SelectValue placeholder="Select sale invoice"/></SelectTrigger><SelectContent>{data.sales.filter(s=>s.status==="completed").slice().reverse().map(s=><SelectItem key={s.id} value={s.id}>{s.invoiceNumber} · {new Date(s.date).toLocaleDateString()}</SelectItem>)}</SelectContent></Select>{selectedSale&&<div className="mt-3 space-y-2">{selectedSale.items.map(i=><div key={i.medicineId} className="flex items-center gap-2"><span className="flex-1 text-sm">{data.medicines.find(m=>m.id===i.medicineId)?.name||i.medicineId} (sold {i.quantity})</span><Input className="w-24" type="number" min={0} max={i.quantity} value={saleReturnQty[i.medicineId]||""} onChange={e=>setSaleReturnQty(x=>({...x,[i.medicineId]:Number(e.target.value)}))}/></div>)}<Button className="mt-2" onClick={makeSaleReturn}><ArrowDownLeft className="mr-2 h-4 w-4"/>Record sales return</Button></div>}</div><div className="surface-card p-5"><h2 className="font-display font-semibold">Purchase return</h2><Select value={purchaseId} onValueChange={setPurchaseId}><SelectTrigger className="mt-3"><SelectValue placeholder="Select supplier invoice"/></SelectTrigger><SelectContent>{data.purchases.slice().reverse().map(p=><SelectItem key={p.id} value={p.id}>{p.invoiceNumber}</SelectItem>)}</SelectContent></Select>{selectedPurchase&&<div className="mt-3 space-y-2">{selectedPurchase.items.map(i=><div key={i.medicineId} className="flex items-center gap-2"><span className="flex-1 text-sm">{data.medicines.find(m=>m.id===i.medicineId)?.name||i.medicineId} (received {i.quantity})</span><Input className="w-24" type="number" min={0} max={i.quantity} value={purchaseReturnQty[i.medicineId]||""} onChange={e=>setPurchaseReturnQty(x=>({...x,[i.medicineId]:Number(e.target.value)}))}/></div>)}<Button className="mt-2" onClick={makePurchaseReturn}><ArrowUpRight className="mr-2 h-4 w-4"/>Record purchase return</Button></div>}</div></div></TabsContent>}
  {canCustomers&&<TabsContent value="customers" className="mt-4"><div className="surface-card p-5"><h2 className="font-display font-semibold">Customer credit / ledger</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr,140px,1fr,auto]"><Select value={customerId} onValueChange={setCustomerId}><SelectTrigger><SelectValue placeholder="Customer"/></SelectTrigger><SelectContent>{data.customers.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select><Input type="number" placeholder="Payment" value={paymentAmount||""} onChange={e=>setPaymentAmount(Number(e.target.value))}/><Input placeholder="Note" value={paymentNote} onChange={e=>setPaymentNote(e.target.value)}/><Button onClick={recordCustomerPayment}>Record payment</Button></div><div className="mt-5 divide-y">{customerRows.map(c=><div key={c.id} className="flex items-center justify-between py-3"><span><b>{c.name}</b><span className="ml-2 text-xs text-muted-foreground">{c.phone||""}</span></span><span className="font-semibold">{money(c.due,sym)} due</span></div>)}</div></div></TabsContent>}
  {canSuppliers&&<TabsContent value="suppliers" className="mt-4"><div className="surface-card p-5"><h2 className="font-display font-semibold">Supplier payables / ledger</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr,140px,1fr,auto]"><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue placeholder="Supplier"/></SelectTrigger><SelectContent>{data.suppliers.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Input type="number" placeholder="Payment" value={paymentAmount||""} onChange={e=>setPaymentAmount(Number(e.target.value))}/><Input placeholder="Note" value={paymentNote} onChange={e=>setPaymentNote(e.target.value)}/><Button onClick={recordSupplierPayment}>Record payment</Button></div><div className="mt-5 divide-y">{supplierRows.map(s=><div key={s.id} className="flex items-center justify-between py-3"><span><b>{s.name}</b><span className="ml-2 text-xs text-muted-foreground">{s.company||""}</span></span><span className="font-semibold">{money(s.due,sym)} payable</span></div>)}</div></div></TabsContent>}
  </Tabs></div>;
}
