import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";
import { Boxes, AlertTriangle, CalendarX, PackageX, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useProjectStore } from "@/store/project-store";
import { daysUntil } from "@/lib/format";
import { PermissionGate } from "@/components/PermissionGate";
import { pinContext } from "@/lib/pins";
import { getBatchReconciliation, isBatchExpired, reconcileMedicineStock } from "@/lib/inventory-engine";

export const Route = createFileRoute("/app/inventory")({ component: () => <PermissionGate perm="inventory"><InventoryPage /></PermissionGate> });
function InventoryPage(){
  const data=useProjectStore(s=>s.data!); const mutate=useProjectStore(s=>s.mutate); const meds=data.medicines; const batches=data.settings.inventoryBatches??[];
  const groups=useMemo(()=>{const low:typeof meds=[],out:typeof meds=[],nearExp:typeof meds=[],exp:typeof meds=[];for(const m of meds){if(m.stockQuantity===0)out.push(m);else if(m.stockQuantity<=(m.minimumStock??0))low.push(m);const d=daysUntil(m.expiryDate);if(d!==null){if(d<0)exp.push(m);else if(d<=30)nearExp.push(m)}}return{low,out,nearExp,exp}},[meds]);
  const reconciliation=useMemo(()=>getBatchReconciliation(data),[data]); const expiredLots=useMemo(()=>batches.filter(b=>b.quantity>0&&isBatchExpired(b.expiryDate)),[batches]);
  function reconcile(){mutate(d=>reconcileMedicineStock(d));toast.success("Medicine stock totals reconciled from batch quantities")}
  return <div className="mx-auto max-w-6xl p-6 md:p-8"><header className="mb-5 flex flex-wrap items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-primary to-primary-glow text-primary-foreground shadow-soft"><Boxes className="h-5 w-5"/></div><div><h1 className="font-display text-2xl font-bold">Inventory health</h1><p className="text-sm text-muted-foreground">Live stock, batch safety and expiry controls</p></div><Button className="ml-auto" variant="outline" onClick={reconcile}><RefreshCw className="mr-1.5 h-4 w-4"/>Reconcile batch stock</Button></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><KPI id="outOfStock" icon={<PackageX/>} label="Out of stock" n={groups.out.length} tone="destructive"/><KPI id="lowStock" icon={<AlertTriangle/>} label="Low stock" n={groups.low.length} tone="warning"/><KPI id="expired" icon={<CalendarX/>} label="Expired" n={groups.exp.length} tone="destructive"/><KPI id="nearExpiry" icon={<CalendarX/>} label="Expiring ≤ 30d" n={groups.nearExp.length} tone="warning"/></div>
    <Section title="Expired batches — not sellable" medicines={meds} batches={expiredLots}/>
    <section className="surface-card mt-5 overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><div><div className="text-sm font-semibold">Batch reconciliation</div><p className="text-xs text-muted-foreground">Compares medicine aggregate stock with its lot quantities.</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{reconciliation.length} issue{reconciliation.length===1?"":"s"}</span></div>{reconciliation.length===0?<div className="p-6 text-sm text-muted-foreground">No batch reconciliation differences found.</div>:<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead className="text-right">Batches</TableHead><TableHead className="text-right">Batch qty</TableHead><TableHead className="text-right">Medicine qty</TableHead><TableHead className="text-right">Difference</TableHead><TableHead className="text-right">Expired qty</TableHead></TableRow></TableHeader><TableBody>{reconciliation.map(r=><TableRow key={r.medicineId}><TableCell className="font-medium">{r.medicineName}</TableCell><TableCell className="text-right">{r.batchCount}</TableCell><TableCell className="text-right tabular-nums">{r.totalBatchQuantity}</TableCell><TableCell className="text-right tabular-nums">{r.medicineQuantity}</TableCell><TableCell className={`text-right tabular-nums ${r.difference!==0?"text-destructive":""}`}>{r.difference>0?`+${r.difference}`:r.difference}</TableCell><TableCell className="text-right tabular-nums">{r.expiredQuantity}</TableCell></TableRow>)}</TableBody></Table>}</section>
    <Section title="Out of stock" medicines={groups.out}/><Section title="Low stock" medicines={groups.low}/><Section title="Expired medicine summary" medicines={groups.exp} expiryCol/><Section title="Near expiry (30 days)" medicines={groups.nearExp} expiryCol/>
  </div>
}
function KPI({id,icon,label,n,tone}:{id:string;icon:React.ReactNode;label:string;n:number;tone:string}){const map:Record<string,string>={warning:"text-warning",destructive:"text-destructive"};return <div className="surface-card p-4" {...pinContext({id:`counter:${id}`,label,kind:"counter"})}><div className={`mb-2 flex items-center gap-2 ${map[tone]}`}>{icon}<span className="text-xs font-medium">{label}</span></div><p className="font-display text-3xl font-bold tabular-nums">{n}</p></div>}
function Section({title,medicines,batches,expiryCol}:{title:string;medicines?:any[];batches?:any[];expiryCol?:boolean}){if(medicines&&batches&&batches.length===0)return null;if(!batches&&medicines&&medicines.length===0)return null;const rows=medicines??[];return <section className="surface-card mt-5 overflow-hidden"><div className="border-b px-4 py-2 text-sm font-medium">{title} ({(batches??rows).length})</div>{batches?<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead>Batch</TableHead><TableHead>Expiry</TableHead><TableHead className="text-right">Qty</TableHead></TableRow></TableHeader><TableBody>{batches.map(b=><TableRow key={b.id}><TableCell className="font-medium">{medicines?.find(m=>m.id===b.medicineId)?.name??b.medicineId}</TableCell><TableCell className="font-mono text-xs">{b.batchNumber||"—"}</TableCell><TableCell>{b.expiryDate||"—"}</TableCell><TableCell className="text-right tabular-nums">{b.quantity}</TableCell></TableRow>)}</TableBody></Table>:<Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Batch</TableHead><TableHead className="text-right">Stock</TableHead>{expiryCol&&<TableHead>Expiry</TableHead>}</TableRow></TableHeader><TableBody>{rows.map(m=><TableRow key={m.id}><TableCell className="font-medium">{m.name}</TableCell><TableCell className="font-mono text-xs">{m.batchNumber||"—"}</TableCell><TableCell className="text-right tabular-nums">{m.stockQuantity}</TableCell>{expiryCol&&<TableCell>{m.expiryDate||"—"}</TableCell>}</TableRow>)}</TableBody></Table>}</section>}
