import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Boxes, AlertTriangle, CalendarX, PackageX, RefreshCw, ShoppingCart, Clock3 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useProjectStore } from "@/store/project-store";
import { daysUntil } from "@/lib/format";
import { PermissionGate } from "@/components/PermissionGate";
import { getBatchReconciliation, isBatchExpired, reconcileMedicineStock } from "@/lib/inventory-engine";
import { getDeadStock, getReorderSuggestions } from "@/lib/reorder-engine";
import { StockTakePage } from "@/routes/app.stocktake";

export const Route = createFileRoute("/app/inventory")({ component: () => <PermissionGate perm="inventory"><InventoryPage /></PermissionGate> });
function money(n: number, symbol: string) { return `${symbol}${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`; }
function InventoryPage(){
  const data=useProjectStore(s=>s.data!); const mutate=useProjectStore(s=>s.mutate); const meds=data.medicines; const batches=data.settings.inventoryBatches??[];
  const [leadTimeDays, setLeadTimeDays] = useState(3); const [deadThreshold, setDeadThreshold] = useState(90); const [inventoryTab, setInventoryTab] = useState("overview");
  const groups=useMemo(()=>{const low:typeof meds=[],out:typeof meds=[],nearExp:typeof meds=[],exp:typeof meds=[];for(const m of meds){if(m.stockQuantity===0)out.push(m);else if(m.stockQuantity<=(m.minimumStock??0))low.push(m);const d=daysUntil(m.expiryDate);if(d!==null){if(d<0)exp.push(m);else if(d<=30)nearExp.push(m)}}return{low,out,nearExp,exp}},[meds]);
  const reconciliation=useMemo(()=>getBatchReconciliation(data),[data]); const expiredLots=useMemo(()=>batches.filter(b=>b.quantity>0&&isBatchExpired(b.expiryDate)),[batches]); const reorder=useMemo(()=>getReorderSuggestions(data, leadTimeDays, 30),[data, leadTimeDays]); const deadStock=useMemo(()=>getDeadStock(data, deadThreshold),[data, deadThreshold]);
  const reorderValue=useMemo(()=>reorder.reduce((sum,r)=>{const m=meds.find(x=>x.id===r.medicineId);return sum+r.suggestedOrderQuantity*(m?.purchasePrice??0)},0),[reorder,meds]); const deadValue=useMemo(()=>deadStock.reduce((sum,r)=>sum+r.purchaseValue,0),[deadStock]);
  function reconcile(){mutate(d=>reconcileMedicineStock(d));toast.success("Medicine stock totals reconciled from batch quantities")}
  function createReorderPOs(){if(reorder.length===0){toast.info("No reorder suggestions to create");return}mutate(d=>{const bySupplier=new Map<string,typeof reorder>();for(const row of reorder){const med=d.medicines.find(m=>m.id===row.medicineId);const supplierId=med?.supplierId||"";if(!supplierId)continue;const list=bySupplier.get(supplierId)??[];list.push(row);bySupplier.set(supplierId,list)}let created=0;for(const [supplierId,rows] of bySupplier){const poId=crypto.randomUUID();const poNumber=`PO-RE-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,14)}-${created+1}`;d.settings.purchaseOrders??=[];d.settings.purchaseOrders.push({id:poId,supplierId,poNumber,date:new Date().toISOString(),status:"draft",lines:rows.map(r=>({medicineId:r.medicineId,quantityOrdered:r.suggestedOrderQuantity,unitCost:d.medicines.find(m=>m.id===r.medicineId)?.purchasePrice??0})),notes:`Created from Smart Reorder (${leadTimeDays}-day lead time, 30-day sales velocity)`});created++}if(created===0)throw new Error("No suggested medicines have a supplier assigned")});const withSupplier=reorder.filter(r=>meds.find(m=>m.id===r.medicineId)?.supplierId).length;if(withSupplier===0)toast.warning("No reorder PO created: assign suppliers to the suggested medicines first");else toast.success(`Created ${new Set(reorder.map(r=>meds.find(m=>m.id===r.medicineId)?.supplierId).filter(Boolean)).size} draft purchase order(s)`)}
  return <div className="mx-auto max-w-7xl p-6 md:p-8"><header className="mb-5 flex flex-wrap items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-primary to-primary-glow text-primary-foreground shadow-soft"><Boxes className="h-5 w-5"/></div><div><h1 className="font-display text-2xl font-bold">Inventory health</h1><p className="text-sm text-muted-foreground">Live stock, batch safety, expiry controls and purchasing intelligence</p></div><Button className="ml-auto" variant="outline" onClick={reconcile}><RefreshCw className="mr-1.5 h-4 w-4"/>Reconcile batch stock</Button></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><KPI icon={<PackageX/>} label="Out of stock" n={groups.out.length} tone="destructive"/><KPI icon={<AlertTriangle/>} label="Low stock" n={groups.low.length} tone="warning"/><KPI icon={<CalendarX/>} label="Expired" n={groups.exp.length} tone="destructive"/><KPI icon={<CalendarX/>} label="Expiring ≤ 30d" n={groups.nearExp.length} tone="warning"/><KPI icon={<ShoppingCart/>} label="Reorder" n={reorder.length} tone="warning"/><KPI icon={<Clock3/>} label="Dead stock" n={deadStock.length} tone="warning"/></div>
    <Tabs value={inventoryTab} onValueChange={setInventoryTab} className="mt-5 w-full"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 md:grid-cols-6"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="reorder">Reorder</TabsTrigger><TabsTrigger value="expiry">Expiry & Batches</TabsTrigger><TabsTrigger value="dead">Dead Stock</TabsTrigger><TabsTrigger value="reconcile">Reconciliation</TabsTrigger><TabsTrigger value="stocktake">Stock Take</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-4"><div className="grid gap-4 md:grid-cols-2"><div className="surface-card p-5"><div className="text-sm font-semibold">Stock overview</div><p className="mt-1 text-xs text-muted-foreground">Use the tabs above to manage purchasing, expiry, dead stock, reconciliation and physical stock take separately.</p></div><div className="surface-card p-5"><div className="text-sm font-semibold">Quick health summary</div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span>Out of stock: <b>{groups.out.length}</b></span><span>Low stock: <b>{groups.low.length}</b></span><span>Expired: <b>{groups.exp.length}</b></span><span>Near expiry: <b>{groups.nearExp.length}</b></span></div></div></div></TabsContent>
      <TabsContent value="reorder" className="mt-4"><section className="surface-card mt-5 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b px-4 py-3"><div className="mr-auto"><div className="text-sm font-semibold">Smart reorder</div><p className="text-xs text-muted-foreground">Based on trailing 30-day sales velocity, lead time and minimum stock.</p></div><label className="text-xs text-muted-foreground">Lead time <select className="ml-1 rounded-md border bg-background px-2 py-1 text-foreground" value={leadTimeDays} onChange={e=>setLeadTimeDays(Number(e.target.value))}><option value={1}>1 day</option><option value={3}>3 days</option><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></label><Button size="sm" onClick={createReorderPOs} disabled={reorder.length===0}><ShoppingCart className="mr-1.5 h-4 w-4"/>Create draft PO{reorder.length?` (${reorder.filter(r=>meds.find(m=>m.id===r.medicineId)?.supplierId).length})`:""}</Button></div>{reorder.length===0?<div className="p-6 text-sm text-muted-foreground">No medicines currently need reordering.</div>:<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead className="text-right">Stock</TableHead><TableHead className="text-right">Avg/day</TableHead><TableHead className="text-right">Days left</TableHead><TableHead className="text-right">Reorder point</TableHead><TableHead className="text-right">Suggested qty</TableHead><TableHead className="text-right">Cost</TableHead></TableRow></TableHeader><TableBody>{reorder.map(r=><TableRow key={r.medicineId}><TableCell className="font-medium">{r.medicineName}{!meds.find(m=>m.id===r.medicineId)?.supplierId&&<span className="ml-2 text-xs text-destructive">No supplier</span>}</TableCell><TableCell className="text-right tabular-nums">{r.stockQuantity}</TableCell><TableCell className="text-right tabular-nums">{r.averageDailySales.toFixed(1)}</TableCell><TableCell className="text-right tabular-nums">{r.stockDaysRemaining===null?"—":r.stockDaysRemaining.toFixed(0)}</TableCell><TableCell className="text-right tabular-nums">{r.reorderPoint}</TableCell><TableCell className="text-right font-semibold tabular-nums">{r.suggestedOrderQuantity}</TableCell><TableCell className="text-right tabular-nums">{money(r.suggestedOrderQuantity*(meds.find(m=>m.id===r.medicineId)?.purchasePrice??0),data.settings.currencySymbol)}</TableCell></TableRow>)}</TableBody></Table>}<div className="border-t px-4 py-2 text-xs text-muted-foreground">Suggested purchase value: <span className="font-semibold text-foreground">{money(reorderValue,data.settings.currencySymbol)}</span></div></section></TabsContent>
      <TabsContent value="dead" className="mt-4"><section className="surface-card mt-0 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b px-4 py-3"><div className="mr-auto"><div className="text-sm font-semibold">Dead / slow-moving stock</div><p className="text-xs text-muted-foreground">Stock with no sale for the selected period. New medicines with no sales are included.</p></div><label className="text-xs text-muted-foreground">No sale for <select className="ml-1 rounded-md border bg-background px-2 py-1 text-foreground" value={deadThreshold} onChange={e=>setDeadThreshold(Number(e.target.value))}><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select></label></div>{deadStock.length===0?<div className="p-6 text-sm text-muted-foreground">No dead stock found for this threshold.</div>:<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead className="text-right">Stock</TableHead><TableHead>Last sale</TableHead><TableHead className="text-right">Days inactive</TableHead><TableHead className="text-right">Cost value</TableHead><TableHead className="text-right">Retail value</TableHead></TableRow></TableHeader><TableBody>{deadStock.map(r=><TableRow key={r.medicineId}><TableCell className="font-medium">{r.medicineName}</TableCell><TableCell className="text-right tabular-nums">{r.stockQuantity}</TableCell><TableCell>{r.lastSaleDate?new Date(r.lastSaleDate).toLocaleDateString():"Never sold"}</TableCell><TableCell className="text-right tabular-nums">{r.daysSinceLastSale===null?"—":r.daysSinceLastSale}</TableCell><TableCell className="text-right tabular-nums">{money(r.purchaseValue,data.settings.currencySymbol)}</TableCell><TableCell className="text-right tabular-nums">{money(r.retailValue,data.settings.currencySymbol)}</TableCell></TableRow>)}</TableBody></Table>}<div className="border-t px-4 py-2 text-xs text-muted-foreground">Capital tied in dead stock: <span className="font-semibold text-foreground">{money(deadValue,data.settings.currencySymbol)}</span></div></section></TabsContent>
      <TabsContent value="expiry" className="mt-4"><Section title="Expired batches — not sellable" medicines={meds} batches={expiredLots}/><Section title="Expired medicine summary" medicines={groups.exp} expiryCol/><Section title="Near expiry (30 days)" medicines={groups.nearExp} expiryCol/></TabsContent>
      <TabsContent value="reconcile" className="mt-4"><section className="surface-card mt-0 overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><div><div className="text-sm font-semibold">Batch reconciliation</div><p className="text-xs text-muted-foreground">Compares medicine aggregate stock with its lot quantities.</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{reconciliation.length} issue{reconciliation.length===1?"":"s"}</span></div>{reconciliation.length===0?<div className="p-6 text-sm text-muted-foreground">No batch reconciliation differences found.</div>:<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead className="text-right">Batches</TableHead><TableHead className="text-right">Batch qty</TableHead><TableHead className="text-right">Medicine qty</TableHead><TableHead className="text-right">Difference</TableHead><TableHead className="text-right">Expired qty</TableHead></TableRow></TableHeader><TableBody>{reconciliation.map(r=><TableRow key={r.medicineId}><TableCell className="font-medium">{r.medicineName}</TableCell><TableCell className="text-right">{r.batchCount}</TableCell><TableCell className="text-right tabular-nums">{r.totalBatchQuantity}</TableCell><TableCell className="text-right tabular-nums">{r.medicineQuantity}</TableCell><TableCell className={`text-right tabular-nums ${r.difference!==0?"text-destructive":""}`}>{r.difference>0?`+${r.difference}`:r.difference}</TableCell><TableCell className="text-right tabular-nums">{r.expiredQuantity}</TableCell></TableRow>)}</TableBody></Table>}</section><div className="mt-4 grid gap-4 md:grid-cols-2"><Section title="Out of stock" medicines={groups.out}/><Section title="Low stock" medicines={groups.low}/></div></TabsContent>
      <TabsContent value="stocktake" className="mt-4"><PermissionGate perm="stocktake"><StockTakePage /></PermissionGate></TabsContent>
    </Tabs>
  </div>
}
function KPI({icon,label,n,tone}:{icon:React.ReactNode;label:string;n:number;tone:string}){const map:Record<string,string>={warning:"text-warning",destructive:"text-destructive"};return <div className="surface-card p-4"><div className={`mb-2 flex items-center gap-2 ${map[tone]}`} >{icon}<span className="text-xs font-medium">{label}</span></div><p className="font-display text-3xl font-bold tabular-nums">{n}</p></div>}
function Section({title,medicines,batches,expiryCol}:{title:string;medicines?:any[];batches?:any[];expiryCol?:boolean}){if(medicines&&batches&&batches.length===0)return null;if(!batches&&medicines&&medicines.length===0)return null;const rows=medicines??[];return <section className="surface-card mt-5 overflow-hidden"><div className="border-b px-4 py-2 text-sm font-medium">{title} ({(batches??rows).length})</div>{batches?<Table><TableHeader><TableRow><TableHead>Medicine</TableHead><TableHead>Batch</TableHead><TableHead>Expiry</TableHead><TableHead className="text-right">Qty</TableHead></TableRow></TableHeader><TableBody>{batches.map(b=><TableRow key={b.id}><TableCell className="font-medium">{medicines?.find(m=>m.id===b.medicineId)?.name??b.medicineId}</TableCell><TableCell className="font-mono text-xs">{b.batchNumber||"—"}</TableCell><TableCell>{b.expiryDate||"—"}</TableCell><TableCell className="text-right tabular-nums">{b.quantity}</TableCell></TableRow>)}</TableBody></Table>:<Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Batch</TableHead><TableHead className="text-right">Stock</TableHead>{expiryCol&&<TableHead>Expiry</TableHead>}</TableRow></TableHeader><TableBody>{rows.map(m=><TableRow key={m.id}><TableCell className="font-medium">{m.name}</TableCell><TableCell className="font-mono text-xs">{m.batchNumber||"—"}</TableCell><TableCell className="text-right tabular-nums">{m.stockQuantity}</TableCell>{expiryCol&&<TableCell>{m.expiryDate||"—"}</TableCell>}</TableRow>)}</TableBody></Table>}</section>}
