import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ClipboardCheck, PackageX, RotateCcw, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { PermissionGate } from "@/components/PermissionGate";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { beginStockTake, createDisposition, postStockTake, updateStockTakeLine } from "@/lib/stocktake-engine";

export const Route = createFileRoute("/app/stocktake")({ component: () => <PermissionGate perm="stocktake"><StockTakePage /></PermissionGate> });

function StockTakePage() {
  const data = useProjectStore(s => s.data!); const mutate = useProjectStore(s => s.mutate); const user = useSession(s => s.user);
  const [takeId, setTakeId] = useState(""); const [dispositionKind, setDispositionKind] = useState<"expired"|"damaged"|"supplier_return">("expired"); const [batchId, setBatchId] = useState(""); const [qty, setQty] = useState(1); const [supplierId, setSupplierId] = useState(data.suppliers[0]?.id ?? ""); const [reason, setReason] = useState("");
  const takes = data.settings.stockTakes ?? []; const take = takes.find(x => x.id === takeId);
  const batches = data.settings.inventoryBatches ?? [];
  const candidates = useMemo(() => batches.filter(b => b.quantity > 0 && (dispositionKind !== "expired" || (b.expiryDate && b.expiryDate.slice(0,10) < new Date().toISOString().slice(0,10)))), [batches, dispositionKind]);
  function start() { mutate(d => { const t = beginStockTake(d, user?.username); setTakeId(t.id); }); toast.success("Stock take started"); }
  function post() { if (!take) return; try { mutate(d => postStockTake(d, take.id, user?.username)); toast.success("Stock take posted and batch stock reconciled"); } catch(e) { toast.error(e instanceof Error ? e.message : "Could not post stock take"); } }
  function dispose() { if (!batchId) return toast.error("Select a batch"); try { mutate(d => createDisposition(d, dispositionKind, batchId, qty, reason, dispositionKind === "supplier_return" ? supplierId : undefined, user?.username)); toast.success(dispositionKind === "supplier_return" ? "Supplier return recorded" : dispositionKind === "expired" ? "Expired stock quarantined/written off" : "Damaged stock written off"); setQty(1); setReason(""); } catch(e) { toast.error(e instanceof Error ? e.message : "Disposition failed"); } }
  return <div className="mx-auto max-w-7xl p-6 md:p-8"><header className="mb-6"><p className="text-xs uppercase tracking-widest text-muted-foreground">Inventory control</p><h1 className="font-display text-3xl font-bold">Stock Take & Expiry Control</h1><p className="mt-1 text-sm text-muted-foreground">Count stock by batch, require reasons for variances, and safely remove expired or damaged stock.</p></header>
    <div className="grid gap-5 lg:grid-cols-2">
      <section className="surface-card overflow-hidden"><div className="flex items-center gap-3 border-b p-4"><ClipboardCheck className="h-5 w-5"/><div className="mr-auto"><h2 className="font-semibold">Batch stock take</h2><p className="text-xs text-muted-foreground">Physical count is recorded against each lot.</p></div><Button onClick={start}>New stock take</Button></div>{!take?<div className="p-6 text-sm text-muted-foreground">Start a stock take to count current batch quantities.</div>:<><div className="border-b p-4 text-sm"><b>{take.number}</b><span className="ml-2 rounded-full bg-muted px-2 py-1 text-xs">{take.status}</span></div><Table><TableHeader><TableRow><TableHead>Medicine / batch</TableHead><TableHead className="text-right">System</TableHead><TableHead className="text-right">Counted</TableHead><TableHead className="text-right">Variance</TableHead></TableRow></TableHeader><TableBody>{take.lines.map(line => { const m=data.medicines.find(x=>x.id===line.medicineId); const b=batches.find(x=>x.id===line.batchId); return <TableRow key={line.batchId}><TableCell><div className="font-medium">{m?.name ?? line.medicineId}</div><div className="text-xs text-muted-foreground">Batch {b?.batchNumber || "—"}</div>{line.variance!==0&&<Input className="mt-1 h-8" placeholder="Reason required" defaultValue={line.reason ?? ""} onBlur={e=>mutate(d=>{const t=d.settings.stockTakes?.find(x=>x.id===take.id);if(t){const l=t.lines.find(x=>x.batchId===line.batchId);if(l)l.reason=e.target.value.trim()||undefined;}})}/>}</TableCell><TableCell className="text-right">{line.systemQuantity}</TableCell><TableCell className="text-right"><Input className="ml-auto w-24 text-right" type="number" min={0} value={line.countedQuantity} disabled={take.status!=="draft"} onChange={e=>mutate(d=>{const t=d.settings.stockTakes?.find(x=>x.id===take.id);if(t)updateStockTakeLine(t,line.batchId,Number(e.target.value),line.reason);})}/></TableCell><TableCell className={`text-right font-semibold ${line.variance!==0?"text-destructive":""}`}>{line.variance>0?`+${line.variance}`:line.variance}</TableCell></TableRow>})}</TableBody></Table><div className="flex items-center justify-between border-t p-4"><span className="text-xs text-muted-foreground">Every shortage/surplus needs a reason before posting.</span><Button onClick={post} disabled={take.status!=="draft"}>Post stock take</Button></div></>}</section>
      <section className="surface-card overflow-hidden"><div className="flex items-center gap-3 border-b p-4"><PackageX className="h-5 w-5"/><div><h2 className="font-semibold">Expired / damaged / supplier return</h2><p className="text-xs text-muted-foreground">Removes only the selected batch quantity and preserves an audit record.</p></div></div><div className="grid gap-3 p-4"><div><Label>Action</Label><Select value={dispositionKind} onValueChange={v=>setDispositionKind(v as typeof dispositionKind)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="expired">Expired stock</SelectItem><SelectItem value="damaged">Damaged stock</SelectItem><SelectItem value="supplier_return">Return to supplier</SelectItem></SelectContent></Select></div><div><Label>Batch</Label><Select value={batchId} onValueChange={setBatchId}><SelectTrigger><SelectValue placeholder="Select batch"/></SelectTrigger><SelectContent>{candidates.map(b=><SelectItem key={b.id} value={b.id}>{data.medicines.find(m=>m.id===b.medicineId)?.name} · {b.batchNumber||"—"} · Qty {b.quantity}{b.expiryDate?` · ${b.expiryDate}`:""}</SelectItem>)}</SelectContent></Select></div>{dispositionKind==="supplier_return"&&<div><Label>Supplier</Label><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{data.suppliers.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div>}<div><Label>Quantity</Label><Input type="number" min={1} value={qty} onChange={e=>setQty(Number(e.target.value))}/></div><div><Label>Reason</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required reason / supplier reference"/></div><Button onClick={dispose}><RotateCcw className="mr-2 h-4 w-4"/>{dispositionKind==="supplier_return"?"Record supplier return":"Record stock disposition"}</Button><div className="rounded-lg border p-3 text-xs text-muted-foreground"><ShieldAlert className="mr-1 inline h-4 w-4"/>Expired action is only allowed for batches whose expiry date has passed. Inventory is recalculated from batch quantities after every disposition.</div></div></section>
    </div>
  </div>;
}
