/*
 * HPMS security bootstrap.
 *
 * main.cjs intentionally remains the application entry point. This wrapper
 * hardens its existing LAN HTTP server without changing the UI or the
 * application's single-computer behavior.
 */
const http = require("node:http");
const os = require("node:os");
const crypto = require("node:crypto");

const SESSION_TTL_MS = 8 * 60 * 60 * 1000;
const sessions = new Map();
let revision = 0;

function privateHost() {
  const nets = os.networkInterfaces();
  for (const entries of Object.values(nets)) {
    for (const entry of entries || []) {
      if (entry.family !== "IPv4" || entry.internal) continue;
      const p = entry.address.split(".").map(Number);
      if (p[0] === 10 || (p[0] === 192 && p[1] === 168) || (p[0] === 172 && p[1] >= 16 && p[1] <= 31)) return entry.address;
    }
  }
  return "127.0.0.1";
}

function tokenFrom(req) {
  const value = req.headers["x-hpms-session"];
  return typeof value === "string" ? value : "";
}

function validSession(token) {
  const s = sessions.get(token);
  if (!s) return false;
  if (s.expiresAt <= Date.now()) {
    sessions.delete(token);
    return false;
  }
  s.expiresAt = Date.now() + SESSION_TTL_MS;
  return true;
}

function jsonError(res, status, error) {
  const body = JSON.stringify({ error });
  res.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(body) });
  res.end(body);
}

const originalCreateServer = http.createServer;
http.createServer = function secureCreateServer(...args) {
  const originalListener = typeof args[0] === "function" ? args[0] : null;
  if (!originalListener) return originalCreateServer.apply(http, args);

  args[0] = (req, res) => {
    const pathname = (() => {
      try { return new URL(req.url, `http://${req.headers.host || "localhost"}`).pathname; }
      catch { return ""; }
    })();

    // Wrap the response so the existing /login, /project and /revision
    // responses can seed the security layer without changing main.cjs.
    const originalEnd = res.end.bind(res);
    let chunks = [];
    const originalWrite = res.write.bind(res);
    res.write = function captureWrite(chunk, ...rest) {
      if (chunk) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)));
      return originalWrite(chunk, ...rest);
    };
    res.end = function captureEnd(chunk, ...rest) {
      if (chunk) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)));
      try {
        const body = Buffer.concat(chunks).toString("utf8");
        const parsed = body ? JSON.parse(body) : null;
        if (parsed?.sessionId && pathname === "/login") {
          sessions.set(parsed.sessionId, { expiresAt: Date.now() + SESSION_TTL_MS });
        }
        if (typeof parsed?.revision === "number") revision = parsed.revision;
        if (pathname === "/logout" && req.method === "POST") sessions.delete(tokenFrom(req));
      } catch {}
      return originalEnd(chunk, ...rest);
    };

    if (pathname === "/health" || pathname === "/login" || (pathname === "/logout" && req.method === "OPTIONS")) {
      return originalListener(req, res);
    }

    if (req.method === "OPTIONS") return originalListener(req, res);

    if (!validSession(tokenFrom(req))) return jsonError(res, 401, "Authentication required");

    // Prevent a stale client from silently overwriting a newer server state.
    if (pathname === "/project" && req.method === "PUT") {
      const expected = Number(req.headers["x-hpms-revision"]);
      if (Number.isFinite(expected) && expected !== revision) {
        return jsonError(res, 409, "Project changed on the server; pull the latest data before saving.");
      }
    }

    return originalListener(req, res);
  };

  const server = originalCreateServer.apply(http, args);
  const originalListen = server.listen.bind(server);
  server.listen = function secureListen(...listenArgs) {
    // Preserve an explicitly supplied host, otherwise bind to a private LAN
    // interface instead of 0.0.0.0. This is still compatible with HPMS LAN
    // clients and avoids accidental public-interface exposure.
    if (listenArgs.length === 1 && typeof listenArgs[0] === "number") {
      return originalListen(listenArgs[0], privateHost());
    }
    return originalListen(...listenArgs);
  };
  return server;
};

// Fail closed if the application ever tries to use a predictable token in
// future code paths; session IDs generated by main.cjs remain UUIDs.
void crypto;
require("./main.cjs");
