import { useEffect, useRef } from "react";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
import { getRecentEvents, type AuditEntry } from "@/lib/audit-log";
import { useNotificationStore, type NotificationType } from "@/store/notification-store";
import { DEFAULT_NOTIFICATION_PREFERENCES } from "@/lib/notification-types";
import type { PharmacySettings } from "@/domain/schema";
import { isPrescriptionDue, isPrescriptionDueSoon, isPrescriptionVisible, type Prescription } from "@/lib/prescriptions";
const NOTIFICATION_CURSOR_KEY="medicore.admin-notification-audit-cursor";
function readCursor():string|null{try{return localStorage.getItem(NOTIFICATION_CURSOR_KEY);}catch{return null;}}
function writeCursor(iso:string){try{localStorage.setItem(NOTIFICATION_CURSOR_KEY,iso);}catch{}}
function enabled(type:NotificationType,prefs:Record<string,boolean>,settings:PharmacySettings|undefined){const legacy:Partial<Record<NotificationType,boolean|undefined>>={medicineDelete:settings?.notifyOnDeleteMedicine,medicineAdd:settings?.notifyOnAddMedicine,customerAdd:settings?.notifyOnAddCustomer,forceSale:settings?.notifyOnForceSale,largeSale:settings?.notifyOnLargeSale};if(legacy[type]!==undefined)return legacy[type]===true;return prefs[type]??DEFAULT_NOTIFICATION_PREFERENCES[type];}
function matchType(e:AuditEntry,threshold:number):NotificationType|null{if(e.entityType==="medicine"&&e.action==="delete")return"medicineDelete";if(e.entityType==="medicine"&&e.action==="add")return"medicineAdd";if(e.entityType==="medicine"&&e.action==="edit")return"medicineEdit";if(e.entityType==="customer"&&e.action==="add")return"customerAdd";if(e.entityType==="customer"&&e.action==="edit")return"customerEdit";if(e.entityType==="customer"&&e.action==="delete")return"customerDelete";if(e.entityType==="sale"&&e.action==="force-sale")return"forceSale";if(e.entityType==="sale"&&e.action==="add")return(e.price??0)>threshold&&threshold>0?"largeSale":"saleCompleted";if(e.entityType==="sale"&&e.action==="edit")return"saleEdited";if(e.entityType==="purchase"&&e.action==="add")return"purchaseAdd";if(e.entityType==="purchase"&&e.action==="edit")return"purchaseEdit";if(e.entityType==="purchase"&&e.action==="delete")return"purchaseDelete";if(e.entityType==="supplier"&&e.action==="add")return"supplierAdd";if(e.entityType==="supplier"&&e.action==="edit")return"supplierEdit";if(e.entityType==="supplier"&&e.action==="delete")return"supplierDelete";if(e.entityType==="category"&&e.action==="add")return"categoryAdd";if(e.entityType==="category"&&e.action==="edit")return"categoryEdit";if(e.entityType==="category"&&e.action==="delete")return"categoryDelete";return null;}
export function useAdminNotifications(){const settings=useProjectStore(s=>s.data?.settings);const data=useProjectStore(s=>s.data);const user=useSession(s=>s.user);const add=useNotificationStore(s=>s.add);const active=!!user&&(user.role==="admin"||user.permissions.viewNotifications===true);const prefs=settings?.notificationPreferences??{};const threshold=settings?.largeSaleThreshold??0;const snapshot=useRef<string>("");const prescriptionSnapshot=useRef<string>("");
  useEffect(()=>{if(!active||!user)return;let cancelled=false;let timer:number|null=null;let cursor=readCursor();if(!cursor)cursor=new Date(Date.now()-86400000).toISOString();const tick=async()=>{if(cancelled||!cursor)return;try{const parsed=Date.parse(cursor);const events=(await getRecentEvents(new Date(Math.max(0,parsed-1)).toISOString())) as AuditEntry[];if(cancelled)return;let newest=cursor;for(const e of events){if(e.timestamp>newest)newest=e.timestamp;if(e.userId&&e.userId===user.id)continue;const type=matchType(e,threshold);if(!type||!enabled(type,prefs,settings))continue;add({id:`audit:${e.id}:${user.id}`,type,username:e.username||"Someone",timestamp:e.timestamp,entityId:e.entityId,recipientUserId:user.id,medicineName:e.medicineName,quantity:e.quantity,price:e.price});}if(events.length>0){cursor=newest;writeCursor(cursor);}}catch(e){console.error("[notifications] audit sync failed",e);}if(!cancelled)timer=window.setTimeout(tick,1000);};void tick();return()=>{cancelled=true;if(timer!==null)window.clearTimeout(timer);};},[active,user,prefs,threshold,settings,add]);
  useEffect(()=>{if(!active||!user||!data)return;const key=JSON.stringify({sr:data.settings.saleReturns?.map(x=>x.id)??[],pr:data.settings.purchaseReturns?.map(x=>x.id)??[],cp:data.settings.customerLedger?.map(x=>x.id)??[],sp:data.settings.supplierLedger?.map(x=>x.id)??[]});if(!snapshot.current){snapshot.current=key;return;}if(snapshot.current===key)return;const old=JSON.parse(snapshot.current) as {sr:string[];pr:string[];cp:string[];sp:string[]};const now={sr:data.settings.saleReturns?.map(x=>x.id)??[],pr:data.settings.purchaseReturns?.map(x=>x.id)??[],cp:data.settings.customerLedger?.map(x=>x.id)??[],sp:data.settings.supplierLedger?.map(x=>x.id)??[]};const addNew=(ids:string[],oldIds:string[],type:NotificationType,username?:string)=>{for(const id of ids.filter(x=>!oldIds.includes(x))){if(username&&username===user.username)continue;if(!enabled(type,prefs,settings))continue;add({id:`state:${type}:${id}:${user.id}`,type,username:username||"Someone",timestamp:new Date().toISOString(),entityId:id,recipientUserId:user.id});}};for(const r of data.settings.saleReturns??[])if(now.sr.includes(r.id)&&!old.sr.includes(r.id))addNew([r.id],old.sr,"saleReturned",r.createdBy);for(const r of data.settings.purchaseReturns??[])if(now.pr.includes(r.id)&&!old.pr.includes(r.id))addNew([r.id],old.pr,"purchaseReturned",r.createdBy);for(const r of data.settings.customerLedger??[])if(now.cp.includes(r.id)&&!old.cp.includes(r.id))addNew([r.id],old.cp,"customerPayment",r.createdBy);for(const r of data.settings.supplierLedger??[])if(now.sp.includes(r.id)&&!old.sp.includes(r.id))addNew([r.id],old.sp,"supplierPayment",r.createdBy);snapshot.current=key;},[active,user,data,prefs,settings,add]);
  useEffect(()=>{if(!active||!user||!data)return;const list=data.settings.prescriptions??[];const current=JSON.stringify(list.map(p=>({id:p.id,date:p.date,next:p.nextVisitDate,visibility:p.visibility,allowed:p.allowedUserIds,patient:p.patientName,createdBy:p.createdBy})));
    if(!prescriptionSnapshot.current){prescriptionSnapshot.current=current;return;}
    const old=JSON.parse(prescriptionSnapshot.current) as Array<{id:string;date:string;next?:string;visibility:string;allowed?:string[];patient:string;createdBy?:string}>;
    const oldMap=new Map(old.map(p=>[p.id,p]));
    for(const p of list){const previous=oldMap.get(p.id);const visible=isPrescriptionVisible(p,user);if(!visible)continue;if(!previous){if(p.createdBy===user.username)continue;if(enabled("prescriptionAdd",prefs,settings))add({id:`rx:add:${p.id}:${user.id}`,type:"prescriptionAdd",username:p.createdBy||"Someone",timestamp:new Date().toISOString(),entityId:p.id,recipientUserId:user.id,details:`New prescription for ${p.patientName}`});}else if(previous.date===p.date&&JSON.stringify(previous)!==JSON.stringify({id:p.id,date:p.date,next:p.nextVisitDate,visibility:p.visibility,allowed:p.allowedUserIds,patient:p.patientName,createdBy:p.createdBy})&&p.createdBy!==user.username&&enabled("prescriptionEdit",prefs,settings)){add({id:`rx:edit:${p.id}:${p.nextVisitDate ?? ""}:${user.id}`,type:"prescriptionEdit",username:p.createdBy||"Someone",timestamp:new Date().toISOString(),entityId:p.id,recipientUserId:user.id,details:`Prescription updated for ${p.patientName}`});}}
    for(const p of old)if(!list.some(x=>x.id===p.id)&&isPrescriptionVisible(p,user)&&p.createdBy!==user.username&&enabled("prescriptionDelete",prefs,settings))add({id:`rx:delete:${p.id}:${user.id}`,type:"prescriptionDelete",username:p.createdBy||"Someone",timestamp:new Date().toISOString(),entityId:p.id,recipientUserId:user.id,details:`Prescription deleted for ${p.patient}`});
    prescriptionSnapshot.current=current;
  },[active,user,data,prefs,settings,add]);
  useEffect(()=>{if(!active||!user||!data)return;const check=()=>{const now=new Date().toISOString().slice(0,10);for(const p of data.settings.prescriptions??[]){if(!isPrescriptionVisible(p,user)||!p.nextVisitDate)continue;const type=isPrescriptionDue(p,now)?"prescriptionDueToday":isPrescriptionDueSoon(p,now)?"prescriptionDueSoon":null;if(!type||!enabled(type,prefs,settings))continue;add({id:`rx:${type}:${p.id}:${p.nextVisitDate}:${user.id}`,type,username:p.createdBy||"System",timestamp:new Date().toISOString(),entityId:p.id,recipientUserId:user.id,details:`${p.patientName} is scheduled for ${p.nextVisitDate}`});if(p.items.some(x=>(data.medicines.find(m=>m.id===x.medicineId)?.stockQuantity??0)<x.quantity)&&enabled("prescriptionMedicineOutOfStock",prefs,settings))add({id:`rx:stock:${p.id}:${p.nextVisitDate}:${user.id}`,type:"prescriptionMedicineOutOfStock",username:"System",timestamp:new Date().toISOString(),entityId:p.id,recipientUserId:user.id,details:`${p.patientName}'s prescription has medicine below the required stock`});}};check();const id=window.setInterval(check,60000);return()=>window.clearInterval(id);},[active,user,data,prefs,settings,add]);
}
