import { useMemo, useState } from "react";
import { Bell, Trash2, X, Pill, UserPlus, ShoppingCart, AlertTriangle, Search, RotateCcw, Truck, Users, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useNotificationStore, type NotificationItem } from "@/store/notification-store";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
import { NOTIFICATION_LABELS } from "@/lib/notification-types";
import { money } from "@/lib/format";

const ICONS: Record<string, typeof Bell> = { saleCompleted: ShoppingCart, forceSale: AlertTriangle, largeSale: AlertTriangle, medicineAdd: Pill, medicineEdit: Pill, medicineDelete: Pill, medicineLowStock: Pill, medicineOutOfStock: Pill, customerAdd: UserPlus, customerEdit: Users, customerDelete: Users, customerPayment: Users, purchaseAdd: Truck, purchaseEdit: Truck, purchaseDelete: Truck, purchaseReturned: RotateCcw, saleReturned: RotateCcw, syncConflict: ShieldAlert, dataSaveFailed: ShieldAlert };
function summarize(n: NotificationItem, sym: string): string { const label = NOTIFICATION_LABELS[n.type] ?? n.type; if (n.type === "saleCompleted") return `${n.username} completed a sale of ${money(n.price ?? 0, sym)}`; if (n.type === "largeSale") return `${n.username} made a large sale of ${money(n.price ?? 0, sym)}`; if (n.type === "forceSale") return `${n.username} force-sold ${n.quantity ?? 0} × "${n.medicineName ?? "item"}"`; if (n.medicineName) return `${n.username}: ${label} — "${n.medicineName}"`; return `${n.username}: ${label}`; }

export function NotificationBell() {
  const user = useSession((s) => s.user);
  const items = useNotificationStore((s) => s.items), remove = useNotificationStore((s) => s.remove), clearAll = useNotificationStore((s) => s.clearAll), markRead = useNotificationStore((s) => s.markRead), markAllRead = useNotificationStore((s) => s.markAllRead);
  const sym = useProjectStore((s) => s.data?.settings.currencySymbol || "$");
  const [open, setOpen] = useState(false); const [detail, setDetail] = useState<NotificationItem | null>(null); const [query, setQuery] = useState("");
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return items; return items.filter((n) => `${NOTIFICATION_LABELS[n.type] ?? n.type} ${n.username} ${n.medicineName ?? ""} ${n.details ?? ""}`.toLowerCase().includes(q)); }, [items, query]);
  const allowed = !!user && (user.role === "admin" || user.permissions.viewNotifications === true);
  if (!allowed) return null;
  const unread = items.filter((i) => !i.read).length;
  return <><Popover open={open} onOpenChange={(v) => { setOpen(v); if (v) markAllRead(); }}><PopoverTrigger asChild><Button variant="ghost" size="icon" className="relative" title="Notifications"><Bell className="h-4 w-4" />{unread > 0 && <span className="absolute -right-0.5 -top-0.5 grid h-4 min-w-4 place-items-center rounded-full bg-destructive px-1 text-[10px] font-semibold text-destructive-foreground">{unread > 99 ? "99+" : unread}</span>}</Button></PopoverTrigger><PopoverContent align="end" className="w-[min(420px,calc(100vw-24px))] p-0"><div className="border-b px-4 py-3"><div className="flex items-center justify-between"><span className="font-display text-sm font-semibold">Notifications</span>{items.length > 0 && <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={clearAll}>Clear all</Button>}</div><div className="relative mt-2"><Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search notifications…" className="h-8 pl-8 text-xs" /></div></div><ScrollArea className="h-[min(480px,60vh)]">{filtered.length === 0 ? <p className="p-6 text-center text-sm text-muted-foreground">{items.length ? "No matching notifications." : "Nothing yet."}</p> : <div className="divide-y">{filtered.map((n) => { const Icon = ICONS[n.type] ?? Bell; return <div key={n.id} className="group flex cursor-pointer items-start gap-3 px-4 py-3 text-sm hover:bg-accent" onClick={() => { markRead(n.id); setOpen(false); setTimeout(() => setDetail(n), 0); }}>{!n.read && <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary" />}<Icon className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate">{summarize(n, sym)}</p><p className="text-xs text-muted-foreground">{new Date(n.timestamp).toLocaleString()}</p></div><button className="shrink-0 rounded p-1 opacity-0 hover:bg-muted group-hover:opacity-100" onClick={(e) => { e.stopPropagation(); remove(n.id); }} title="Delete"><X className="h-3.5 w-3.5 text-muted-foreground" /></button></div>; })}</div>}</ScrollArea></PopoverContent></Popover><NotificationDetailDialog notification={detail} onClose={() => setDetail(null)} onDelete={remove} /></>;
}

function NotificationDetailDialog({ notification, onClose, onDelete }: { notification: NotificationItem | null; onClose: () => void; onDelete: (id: string) => void }) { const data = useProjectStore((s) => s.data); const sym = data?.settings.currencySymbol || "$"; const sale = notification?.type === "saleCompleted" || notification?.type === "forceSale" || notification?.type === "largeSale" ? data?.sales.find((s) => s.id === notification.entityId) : null; return <Dialog open={!!notification} onOpenChange={(o) => !o && onClose()}><DialogContent className="max-w-md">{notification && <><DialogHeader><DialogTitle>{summarize(notification, sym)}</DialogTitle></DialogHeader><p className="-mt-2 text-xs text-muted-foreground">{new Date(notification.timestamp).toLocaleString()}</p>{notification.type === "forceSale" && <div className="mt-2 rounded-md border border-warning/30 bg-warning/10 p-3 text-sm"><p className="font-medium text-warning">Forced sale</p><p>{notification.quantity ?? 0} unit(s) of {notification.medicineName ?? "the item"} were sold beyond available stock.</p></div>}{sale && <div className="mt-2"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-2 font-medium">Name</th><th className="pb-2 text-right font-medium">Qty</th><th className="pb-2 text-right font-medium">Price</th></tr></thead><tbody>{sale.items.map((it, i) => { const med = data?.medicines.find((m) => m.id === it.medicineId); return <tr key={i} className="border-b last:border-0"><td className="py-1.5">{med?.name ?? "—"}</td><td className="py-1.5 text-right tabular-nums">{it.quantity}</td><td className="py-1.5 text-right tabular-nums">{money(it.salePrice, sym)}</td></tr>; })}</tbody></table></div>}{notification.details && <p className="mt-3 rounded-md bg-muted p-3 text-sm">{notification.details}</p>}<div className="mt-4 flex justify-end"><Button variant="outline" size="sm" onClick={() => { onDelete(notification.id); onClose(); }}><Trash2 className="mr-1.5 h-3.5 w-3.5" /> Delete notification</Button></div></>}</DialogContent></Dialog>; }
