import { useMemo, useState } from "react";
import { useProjectStore } from "@/store/project-store";
import { useSession } from "@/store/session-store";
import { uid, money } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

export function PharmacyControls() {
  const data = useProjectStore(s => s.data!); const mutate = useProjectStore(s => s.mutate); const user = useSession(s => s.user); const sym = data.settings.currencySymbol || "₨";
  const [supplierId,setSupplierId]=useState(data.suppliers[0]?.id||""); const [pay,setPay]=useState(0); const [payNote,setPayNote]=useState("");
  const [medicineId,setMedicineId]=useState(data.medicines[0]?.id||""); const [count,setCount]=useState(0); const [reason,setReason]=useState("Count adjustment");
  const [writeMedicine,setWriteMedicine]=useState(data.medicines[0]?.id||""); const [writeQty,setWriteQty]=useState(0); const [writeReason,setWriteReason]=useState("Expired");
  const [controlMedicine,setControlMedicine]=useState(data.medicines[0]?.id||"");
  const [fbrEnabled,setFbrEnabled]=useState(Boolean(data.settings.fbr?.enabled)); const [ntn,setNtn]=useState(data.settings.fbr?.ntn||""); const [strn,setStrn]=useState(data.settings.fbr?.strn||""); const [posId,setPosId]=useState(data.settings.fbr?.posId||"");
  const suppliers=useMemo(()=>data.suppliers.map(s=>{const purchases=data.purchases.filter(p=>p.supplierId===s.id).reduce((a,p)=>a+p.items.reduce((x,i)=>x+i.quantity*i.purchasePrice,0)-p.discount,0);const returns=(data.settings.purchaseReturns||[]).filter(r=>r.supplierId===s.id).reduce((a,r)=>a+r.items.reduce((x,i)=>x+i.quantity*i.purchasePrice,0),0);const payments=(data.settings.supplierLedger||[]).filter(e=>e.supplierId===s.id&&e.type==="payment").reduce((a,e)=>a+e.amount,0);return {...s,due:Math.max(0,purchases-returns-payments)};}),[data]);
  const selectedSupplier=suppliers.find(s=>s.id===supplierId); const med=data.medicines.find(m=>m.id===medicineId); const wmed=data.medicines.find(m=>m.id===writeMedicine);
  function supplierPayment(){if(!supplierId||pay<=0)return toast.error("Select supplier and payment amount");mutate(d=>{d.settings.supplierLedger=[...(d.settings.supplierLedger||[]),{id:uid("sl_"),supplierId,date:new Date().toISOString(),type:"payment",amount:pay,note:payNote||undefined,createdBy:user?.username}];const s=d.suppliers.find(x=>x.id===supplierId);if(s)s.balance=Math.max(0,(s.balance||0)-pay);});setPay(0);setPayNote("");toast.success("Supplier payment recorded");}
  function stockTake(){if(!med||count<0)return toast.error("Enter a valid count");mutate(d=>{const m=d.medicines.find(x=>x.id===medicineId);if(!m)return;const delta=count-m.stockQuantity;if(delta===0)return;m.stockQuantity=count;d.stockAdjustments=[...(d.stockAdjustments||[]),{id:uid("stk_"),medicineId,date:new Date().toISOString(),delta,reason,kind:"stocktake",createdBy:user?.username} as any];});toast.success("Physical stock reconciled");}
  function writeOff(){if(!wmed||writeQty<=0||writeQty>wmed.stockQuantity)return toast.error("Enter a valid write-off quantity");mutate(d=>{const m=d.medicines.find(x=>x.id===writeMedicine);if(!m)return;m.stockQuantity-=writeQty;d.stockAdjustments=[...(d.stockAdjustments||[]),{id:uid("wo_"),medicineId:writeMedicine,date:new Date().toISOString(),delta:-writeQty,reason:writeReason,kind:"writeoff",createdBy:user?.username} as any];});toast.success("Stock written off and audited");setWriteQty(0);}
  function saveFbr(){mutate(d=>{d.settings.fbr={enabled:fbrEnabled,ntn:ntn.trim(),strn:strn.trim(),posId:posId.trim(),invoicePrefix:d.settings.fbr?.invoicePrefix||"INV-",nextInvoiceNumber:d.settings.fbr?.nextInvoiceNumber||1};});toast.success("FBR invoice configuration saved");}
  function toggleControlled(){if(!controlMedicine)return;mutate(d=>{const m=d.medicines.find(x=>x.id===controlMedicine);if(m)m.controlledDrug=!m.controlledDrug;});}
  const controlled=data.medicines.filter(m=>m.controlledDrug);
  return <div className="surface-card p-4"><div className="mb-4"><h2 className="font-display text-xl font-semibold">Pharmacy Controls</h2><p className="text-sm text-muted-foreground">Purchasing, compliance, stock reconciliation, write-offs and Pakistan tax configuration.</p></div><Tabs defaultValue="payables"><TabsList className="grid w-full grid-cols-5"><TabsTrigger value="payables">Supplier Payables</TabsTrigger><TabsTrigger value="purchase">Purchase Workflow</TabsTrigger><TabsTrigger value="controlled">Controlled</TabsTrigger><TabsTrigger value="stock">Stock Take</TabsTrigger><TabsTrigger value="fbr">FBR</TabsTrigger></TabsList>
    <TabsContent value="payables" className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><div><Label>Supplier</Label><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue placeholder="Select supplier"/></SelectTrigger><SelectContent>{suppliers.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div><div className="rounded-lg border p-3"><span className="text-xs text-muted-foreground">Outstanding payable</span><div className="text-2xl font-semibold">{money(selectedSupplier?.due||0,sym)}</div></div></div><div className="grid gap-3 md:grid-cols-3"><div><Label>Payment</Label><Input type="number" min={0} value={pay||""} onChange={e=>setPay(Number(e.target.value))}/></div><div><Label>Reference / note</Label><Input value={payNote} onChange={e=>setPayNote(e.target.value)}/></div><div className="flex items-end"><Button onClick={supplierPayment}>Record supplier payment</Button></div></div><div className="rounded-lg border divide-y">{suppliers.sort((a,b)=>b.due-a.due).slice(0,10).map(s=><div key={s.id} className="flex justify-between p-3 text-sm"><span>{s.name}</span><b>{money(s.due,sym)}</b></div>)}</div></TabsContent>
    <TabsContent value="purchase" className="space-y-4"><div className="rounded-lg border p-4"><h3 className="font-semibold">Purchase control checklist</h3><ul className="mt-2 list-disc pl-5 text-sm text-muted-foreground space-y-1"><li>Record supplier invoice and received date.</li><li>Capture batch, expiry and purchase cost for every received line.</li><li>Use supplier payable instead of deleting financial history.</li><li>Use supplier return for goods sent back; it reduces payable and stock.</li></ul></div><div className="rounded-lg border p-4"><h3 className="font-semibold">Open supplier balances</h3>{suppliers.filter(s=>s.due>0).map(s=><div key={s.id} className="flex justify-between border-b py-2 text-sm"><span>{s.name}</span><span>{money(s.due,sym)}</span></div>)}{suppliers.every(s=>s.due<=0)&&<p className="py-4 text-sm text-muted-foreground">No outstanding supplier balances.</p>}</div></TabsContent>
    <TabsContent value="controlled" className="space-y-4"><div className="rounded-lg border p-4"><h3 className="font-semibold">Controlled / restricted medicine flag</h3><p className="mt-1 text-xs text-muted-foreground">Flagging a medicine enables the compliance workflow. Legal schedules and prescription rules must be configured for your jurisdiction.</p><div className="mt-3 flex gap-2"><Select value={controlMedicine} onValueChange={setControlMedicine}><SelectTrigger className="flex-1"><SelectValue/></SelectTrigger><SelectContent>{data.medicines.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={toggleControlled}>Toggle controlled</Button></div></div><div className="rounded-lg border divide-y">{controlled.map(m=><div key={m.id} className="p-3 text-sm"><b>{m.name}</b><span className="ml-2 text-xs text-destructive">Controlled</span><div className="text-xs text-muted-foreground">Sales should be linked to a valid prescription and dispensing record.</div></div>)}{controlled.length===0&&<p className="p-4 text-sm text-muted-foreground">No controlled medicines flagged.</p>}</div></TabsContent>
    <TabsContent value="stock" className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><div><Label>Medicine</Label><Select value={medicineId} onValueChange={setMedicineId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{data.medicines.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Physical count</Label><Input type="number" min={0} value={count} onChange={e=>setCount(Number(e.target.value))}/></div><div><Label>Reason</Label><Input value={reason} onChange={e=>setReason(e.target.value)}/></div></div><div className="rounded-lg border p-3 text-sm">System stock: <b>{med?.stockQuantity??0}</b> · Physical count: <b>{count}</b> · Difference: <b>{(count-(med?.stockQuantity??0))}</b></div><Button onClick={stockTake}>Reconcile physical stock</Button><div className="border-t pt-4"><h3 className="font-semibold">Expired / damaged write-off</h3><div className="mt-3 grid gap-3 md:grid-cols-3"><Select value={writeMedicine} onValueChange={setWriteMedicine}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{data.medicines.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select><Input type="number" min={0} max={wmed?.stockQuantity||0} value={writeQty||""} onChange={e=>setWriteQty(Number(e.target.value))}/><Input value={writeReason} onChange={e=>setWriteReason(e.target.value)}/></div><Button className="mt-3" variant="destructive" onClick={writeOff}>Write off stock</Button></div></TabsContent>
    <TabsContent value="fbr" className="space-y-4"><div className="rounded-lg border p-4"><h3 className="font-semibold">Pakistan FBR / POS configuration</h3><p className="mt-1 text-xs text-muted-foreground">This stores your tax identity and POS identifiers for compliant invoice integration. It does not claim a live FBR connection until credentials/API endpoints are configured.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fbrEnabled} onChange={e=>setFbrEnabled(e.target.checked)}/> Enable FBR-ready invoice fields</label><div></div><div><Label>NTN</Label><Input value={ntn} onChange={e=>setNtn(e.target.value)}/></div><div><Label>STRN</Label><Input value={strn} onChange={e=>setStrn(e.target.value)}/></div><div><Label>POS / Registration ID</Label><Input value={posId} onChange={e=>setPosId(e.target.value)}/></div></div><Button className="mt-3" onClick={saveFbr}>Save FBR configuration</Button></div></TabsContent>
  </Tabs></div>;
}
