import { Mic, MicOff, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";

type Target = HTMLInputElement | HTMLTextAreaElement;
const VOICE_LOCALES: Record<string, string> = { en: "en-US", ur: "ur-PK", ar: "ar-SA", hi: "hi-IN", bn: "bn-BD", pa: "pa-IN", fa: "fa-IR", tr: "tr-TR", id: "id-ID", ms: "ms-MY", es: "es-ES", fr: "fr-FR", de: "de-DE", it: "it-IT", pt: "pt-PT", ru: "ru-RU", zh: "zh-CN", ja: "ja-JP", ko: "ko-KR" };
function setInputValue(target: Target, value: string) { const proto = target instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set; setter?.call(target, value); target.dispatchEvent(new Event("input", { bubbles: true })); target.dispatchEvent(new Event("change", { bubbles: true })); }

export function VoiceSearchOverlay() {
  const [target, setTarget] = useState<Target | null>(null); const [open, setOpen] = useState(false); const [listening, setListening] = useState(false); const [transcript, setTranscript] = useState("");
  const recognitionRef = useRef<any>(null); const targetRef = useRef<Target | null>(null); const transcriptRef = useRef(""); targetRef.current = target;
  useEffect(() => { const update = () => { const el = document.activeElement as Target | null; if (!(el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement)) return; const hint = `${el.placeholder || ""} ${el.getAttribute("aria-label") || ""} ${el.name || ""}`.toLowerCase(); if (!hint.includes("search") && !hint.includes("scan")) return; setTarget(el); targetRef.current = el; }; window.addEventListener("focusin", update); return () => window.removeEventListener("focusin", update); }, []);
  useEffect(() => () => { try { recognitionRef.current?.abort(); } catch {} }, []);
  if (!target) return null;
  const close = () => { try { recognitionRef.current?.stop(); } catch {} recognitionRef.current = null; setListening(false); setOpen(false); };
  const start = () => { const Speech = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!Speech) { window.alert("Voice search is not supported by this Windows installation."); return; } transcriptRef.current = ""; setTranscript(""); const r = new Speech(); recognitionRef.current = r; const code = localStorage.getItem("medicore.language") || "en"; r.lang = VOICE_LOCALES[code] || "en-US"; r.continuous = true; r.interimResults = true; r.onstart = () => setListening(true); r.onerror = () => setListening(false); r.onend = () => setListening(false); r.onresult = (event: any) => { let finalText = transcriptRef.current; let interim = ""; for (let i = event.resultIndex; i < event.results.length; i += 1) { const text = event.results[i]?.[0]?.transcript || ""; if (event.results[i]?.isFinal) finalText = `${finalText} ${text}`.trim(); else interim += text; } transcriptRef.current = finalText; setTranscript(`${finalText} ${interim}`.trim()); }; r.start(); };
  const stop = () => { try { recognitionRef.current?.stop(); } catch {} recognitionRef.current = null; setListening(false); const value = transcriptRef.current.trim(); const currentTarget = targetRef.current; if (value && currentTarget) setInputValue(currentTarget, value); setOpen(false); currentTarget?.focus(); };
  return <><Button type="button" size="icon" variant="ghost" className="fixed right-3 top-2 z-[200] h-8 w-8 rounded-full shadow-sm" title="Voice search" aria-label="Voice search" onMouseDown={(e) => e.preventDefault()} onClick={() => { setOpen(true); setTranscript(""); transcriptRef.current = ""; }}><Mic className="h-4 w-4" /></Button>{open && <div className="fixed inset-0 z-[190] grid place-items-center bg-background/60 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) close(); }}><div className="w-[min(460px,calc(100vw-32px))] rounded-2xl border bg-card p-7 text-center shadow-2xl"><div className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Voice search</div><h2 className="mt-2 font-display text-2xl font-bold">{listening ? "Listening…" : "Ready to listen"}</h2><p className="mt-1 text-sm text-muted-foreground">{listening ? "Speak naturally. Your words appear below the microphone." : "Click the microphone to start speaking."}</p><button type="button" aria-label={listening ? "Stop listening" : "Start listening"} onClick={listening ? stop : start} className={`mx-auto mt-7 grid h-32 w-32 place-items-center rounded-full border-4 shadow-lg transition-transform ${listening ? "scale-105 border-primary bg-primary/15 text-primary" : "border-muted bg-muted/40 text-foreground hover:scale-105"}`}>{listening ? <MicOff className="h-12 w-12" /> : <Mic className="h-12 w-12" />}</button><div className="mt-6 min-h-16 rounded-xl border bg-muted/20 p-4 text-left text-sm">{transcript || <span className="text-muted-foreground">What you say will appear here…</span>}</div><div className="mt-5 flex justify-center"><Button variant="outline" onClick={close}><X className="mr-2 h-4 w-4" />Close</Button></div></div></div>}</>;
}
