import { Mic, MicOff, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";

const VOICE_LOCALES: Record<string,string>={en:"en-US",ur:"ur-PK",ar:"ar-SA",hi:"hi-IN",bn:"bn-BD",pa:"pa-IN",fa:"fa-IR",tr:"tr-TR",id:"id-ID",ms:"ms-MY",es:"es-ES",fr:"fr-FR",de:"de-DE",it:"it-IT",pt:"pt-PT",ru:"ru-RU",zh:"zh-CN",ja:"ja-JP",ko:"ko-KR"};
export function VoiceSearchOverlay(){
 const [target,setTarget]=useState<HTMLInputElement|HTMLTextAreaElement|null>(null); const [listening,setListening]=useState(false); const [open,setOpen]=useState(false); const [pos,setPos]=useState({left:0,top:0}); const recognitionRef=useRef<any>(null);
 useEffect(()=>{const update=()=>{const el=document.activeElement as HTMLInputElement|HTMLTextAreaElement|null;if(!(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement)){setTarget(null);setOpen(false);return}const hint=`${el.placeholder||""} ${el.getAttribute("aria-label")||""} ${el.name||""}`.toLowerCase();if(!hint.includes("search")&&!hint.includes("scan")){setTarget(null);setOpen(false);return}const r=el.getBoundingClientRect();setTarget(el);setPos({left:Math.max(8,r.right-38),top:r.top+(r.height-32)/2})};window.addEventListener("focusin",update);window.addEventListener("scroll",update,true);window.addEventListener("resize",update);update();return()=>{window.removeEventListener("focusin",update);window.removeEventListener("scroll",update,true);window.removeEventListener("resize",update)}},[]);
 if(!target)return null;
 const stop=()=>{try{recognitionRef.current?.stop()}catch{} setListening(false)};
 const start=()=>{const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){alert("Voice search is not supported by this Windows installation.");return}setOpen(true);setListening(false);const r=new Speech();recognitionRef.current=r;const code=localStorage.getItem("medicore.language")||"en";r.lang=VOICE_LOCALES[code]||"en-US";r.interimResults=false;r.continuous=true;r.onstart=()=>setListening(true);r.onerror=()=>setListening(false);r.onend=()=>setListening(false);r.onresult=(e:any)=>{const value=e.results?.[e.results.length-1]?.[0]?.transcript||"";const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(target),"value")?.set;setter?.call(target,value);target.dispatchEvent(new Event("input",{bubbles:true}));target.dispatchEvent(new Event("change",{bubbles:true}));target.focus()};r.start()};
 return <><Button type="button" size="icon" variant={listening?"default":"ghost"} className="fixed z-[200] h-8 w-8 rounded-full shadow-sm" style={{left:pos.left,top:pos.top}} title="Voice search" aria-label="Voice search" onMouseDown={e=>e.preventDefault()} onClick={()=>{if(listening)stop();else start()}}>{listening?<MicOff className="h-4 w-4"/>:<Mic className="h-4 w-4"/>}</Button>{open&&<div className="fixed inset-0 z-[190] grid place-items-center bg-background/40 backdrop-blur-[2px]"><div className="w-[min(420px,calc(100vw-32px))] rounded-2xl border bg-card p-6 text-center shadow-2xl"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-primary/10 text-primary">{listening?<Mic className="h-8 w-8 animate-pulse"/>:<MicOff className="h-8 w-8"/>}</div><h2 className="mt-4 font-display text-xl font-bold">{listening?"Listening…":"Voice search stopped"}</h2><p className="mt-1 text-sm text-muted-foreground">{listening?"Speak your search. Your words will appear in the search field.":"Press Start again or close this panel."}</p><div className="mt-5 flex justify-center gap-2"><Button variant="outline" onClick={()=>{stop();setOpen(false)}}><X className="mr-2 h-4 w-4"/>Close</Button><Button onClick={listening?stop:start}>{listening?<><MicOff className="mr-2 h-4 w-4"/>Stop listening</>:<><Mic className="mr-2 h-4 w-4"/>Start listening</>}</Button></div></div></div>}</>;
}
