/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppMedicinesRouteImport } from './routes/app.medicines'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppShortcutsRouteImport } from './routes/app.shortcuts'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicinesRoute = AppMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShortcutsRoute = AppShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bills': typeof AppBillsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/medicines': typeof AppMedicinesRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortcuts': typeof AppShortcutsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bills': typeof AppBillsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/medicines': typeof AppMedicinesRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortcuts': typeof AppShortcutsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bills': typeof AppBillsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/medicines': typeof AppMedicinesRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortcuts': typeof AppShortcutsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bills'
    | '/app/calculator'
    | '/app/categories'
    | '/app/customers'
    | '/app/inventory'
    | '/app/medicines'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/shortcuts'
    | '/app/suppliers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bills'
    | '/app/calculator'
    | '/app/categories'
    | '/app/customers'
    | '/app/inventory'
    | '/app/medicines'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/shortcuts'
    | '/app/suppliers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bills'
    | '/app/calculator'
    | '/app/categories'
    | '/app/customers'
    | '/app/inventory'
    | '/app/medicines'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/shortcuts'
    | '/app/suppliers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medicines': {
      id: '/app/medicines'
      path: '/medicines'
      fullPath: '/app/medicines'
      preLoaderRoute: typeof AppMedicinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shortcuts': {
      id: '/app/shortcuts'
      path: '/shortcuts'
      fullPath: '/app/shortcuts'
      preLoaderRoute: typeof AppShortcutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMedicinesRoute: typeof AppMedicinesRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShortcutsRoute: typeof AppShortcutsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppCalculatorRoute: AppCalculatorRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMedicinesRoute: AppMedicinesRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShortcutsRoute: AppShortcutsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
